Repository super-linter/super-linter, pull requests merged in 2020-11, with the labels that each got.

#940 Fail on errors while getting linter versions
  lib/linter.sh
  lib/linterVersions.sh
Labels: enhancement, infrastructure

#950 fixing logic
  lib/linter.sh
Labels: bug

#941 Use the already-defined linter names array to print linter versions
  Dockerfile
  lib/linter.sh
  lib/linterVersions.sh
  lib/worker.sh
Labels: enhancement, infrastructure

#956 Update bug issue template with logging instructions
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement

#959 fix find
  lib/buildFileList.sh
Labels: bug

#980 cleanup file
  docs/disabling-linters.md
Labels: documentation

#981 quoting powershell files
  lib/worker.sh
Labels: bug

#990 break out:
  .automation/clean-code-base-for-tests.sh
  .automation/cleanup-docker.sh
  .automation/upload-docker.sh
  .automation/validate-docker-labels.sh
  Dockerfile
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/functions/linterRules.sh
  lib/functions/linterVersions.sh
  lib/functions/log.sh
  lib/functions/possum.sh
  lib/functions/tapLibrary.sh
  lib/functions/validateDocker.sh
  lib/functions/validation.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: automation

#992 give more memory
  lib/linter.sh
Labels: enhancement

#998 Exclude __pycache__ and .pytest_cache from file list
  lib/functions/buildFileList.sh
Labels: enhancement, python

#1011 Gherkin
  .automation/test/gherkin/README.md
  .automation/test/gherkin/gherkin_bad_01.feature
  .automation/test/gherkin/gherkin_good_01.feature
  .automation/test/gherkin/reports/expected-GHERKIN.tap.ignored
  README.md
  TEMPLATES/.gherkin-lintrc
  dependencies/package-lock.json
  dependencies/package.json
  lib/functions/buildFileList.sh
  lib/functions/linterVersions.sh
  lib/linter.sh
Labels: enhancement

#1034 Change log level from warn to debug
  lib/functions/detectFiles.sh
  lib/functions/worker.sh
Labels: enhancement
