Repository super-linter/super-linter, pull requests merged in 2020-09, with the labels that each got.

#649 Streamline shell scripts file list building and bootstrap npm-groovy-lint
  Dockerfile
  README.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: bug, enhancement

#656 Fixing deploy latest
  .automation/upload-docker.sh
Labels: automation, bug

#657 adding new url for GHCR
  .automation/upload-docker.sh
Labels: automation

#663 Adding more paths to ignore
  lib/buildFileList.sh
  lib/worker.sh
Labels: bug, enhancement

#664 Adding more vars
  .automation/upload-docker.sh
  Dockerfile
Labels: docker, enhancement

#670 super simple
  Dockerfile
  lib/linter.sh
  lib/linterVersions.sh
Labels: automation, enhancement

#677 Print version, date and revision
  .automation/upload-docker.sh
  .automation/validate-docker-labels.sh
  .github/workflows/deploy-DEV.yml
  Dockerfile
  lib/linter.sh
Labels: docker, enhancement

#674 Move to GitHub Container Registry
  .github/workflows/stack-linter.yml
  action.yml
Labels: automation, docker

#689 Add `snakemake --lint`/`snakefmt` support to super-linter
  .automation/test/snakemake/README.md
  .automation/test/snakemake/snakemake_bad_1.smk
  .automation/test/snakemake/snakemake_good_1.smk
  .github/linters/.snakefmt.toml
  Dockerfile
  README.md
  TEMPLATES/.snakefmt.toml
  dependencies/Pipfile
  dependencies/Pipfile.lock
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: docker, enhancement

#679 Just filter the .git folder
  lib/worker.sh
Labels: bug

#684 Allow to include and exclude files from linting
  README.md
  lib/linter.sh
  lib/worker.sh
Labels: documentation, enhancement

#711 Minor README improvement: https URL scheme added to some links
  README.md
Labels: documentation

#723 Fix file filters: Reorder arguments to LintCodeBase function
  lib/linter.sh
  lib/worker.sh
Labels: enhancement

#727 adding version
  Dockerfile
Labels: enhancement

#756 Update linter.sh
  lib/linter.sh
Labels: bug

#713 Fix file detection issues of Snakemake linter/formatter
  dependencies/Pipfile.lock
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: bug

#770 Ignore .git and symlink .dockerignore
  .dockerignore
  .gitignore
Labels: enhancement

#777 fix version
  dependencies/Pipfile
  dependencies/Pipfile.lock
Labels: bug
