Repository super-linter/super-linter, pull requests merged in 2020-12, with the labels that each got.

#1049 fixing logic for file find
  .automation/test/terraform/good/terraform_good_1.tf
  .automation/test/terraform_terrascan/bad/terraform-terrascan_bad_1.tf
  .automation/test/terraform_terrascan/good/terraform-terrascan_good_1.tf
  .automation/test/terraform_terrascan/reports/expected-TERRAFORM_TERRASCAN.tap
  .github/workflows/deploy-RELEASE.yml
  lib/functions/buildFileList.sh
Labels: bug

#1051 Try to build with caching to help build times
  .automation/validate-docker-labels.sh
  .github/workflows/deploy-DEV.yml
  .github/workflows/deploy-PROD.yml
  .github/workflows/deploy-RELEASE.yml
Labels: automation, docker

#1035 Simplify linter and worker by generalizing ansible-lint
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: automation, enhancement

#1060 Better deploy
  .github/workflows/deploy-PROD.yml
  .github/workflows/deploy-RELEASE.yml
Labels: bug
