Repository super-linter/super-linter, pull requests merged in 2020-07, with the labels that each got.

#343 Were going to fix it all
  .github/workflows/deploy-DEV.yml
  README.md
  TEMPLATES/.tflint.hcl
  lib/buildFileList.sh
  lib/linter.sh
Labels: bug, documentation, enhancement

#365 Add stalebot workflow
  .github/workflows/stale.yml
Labels: automation, enhancement

#369 Add support for Azure Resource Manager (ARM) linting with [arm-ttk]
  .automation/test/arm/README.md
  .automation/test/arm/arm_bad_1.json
  .automation/test/arm/arm_good_1.json
  Dockerfile
  README.md
  TEMPLATES/.arm-ttk.psd1
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: enhancement

#373 Add HTML support to super-linter
  .automation/test/html/README.md
  .automation/test/html/html_bad_01.html
  .automation/test/html/html_good_01.html
  .github/linters/.htmlhintrc
  Dockerfile
  README.md
  TEMPLATES/.htmlhintrc
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
  package-lock.json
Labels: enhancement

#221 Add `editorconfig-checker`
  .automation/test/editorconfig-checker/.editorconfig
  .automation/test/editorconfig-checker/README.md
  .automation/test/editorconfig-checker/editorconfig-checker_bad_1.ext
  .automation/test/editorconfig-checker/editorconfig-checker_good_1.ext
  .github/linters/.ecrc
  Dockerfile
  README.md
  docs/disabling-linters.md
  lib/linter.sh
  lib/validation.sh
Labels: enhancement, help wanted

#354 Auto draft releases
  .github/CONTRIBUTING.md
  .github/pull_request-template.md
  .github/release-drafter.yml
  .github/workflows/draft-release.yml
Labels: automation

#383 Correct release compare language
  .github/release-drafter.yml
Labels: infrastructure

#388 Shellcheck other extensions
  lib/linter.sh
  lib/worker.sh
Labels: enhancement

#386 docs: correct name for markdown-lint
  docs/disabling-linters.md
Labels: documentation

#384 Fixed config load issue caused by quotes
  lib/linter.sh
Labels: bug

#377 Add basic Raku support
  .automation/test/raku/README.md
  .automation/test/raku/raku_bad_1.raku
  .automation/test/raku/raku_good_1.raku
  Dockerfile
  README.md
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: enhancement

#397 Fix dockerfilelint -c option usage
  lib/linter.sh
Labels: bug, enhancement

#398 Revert "seems to be the simplier path" - Fix dockerfilelint -c option usage
  lib/linter.sh
Labels: automation, bug

#372 Use dependabot for linters dependencies
  .github/dependabot.yml
  Dockerfile
  dependencies/Pipfile
  dependencies/Pipfile.lock
  dependencies/package-lock.json
  dependencies/package.json
  lib/linter.sh
  lib/worker.sh
Labels: automation, dependencies, enhancement

#405 small fix for git folder
  lib/buildFileList.sh
  lib/worker.sh
Labels: bug

#406 adding hold
  .github/workflows/draft-release.yml.hold
Labels: automation

#252 Support TAP reporting format
  .gitignore
  Dockerfile
  README.md
  lib/linter.sh
  lib/worker.sh
Labels: enhancement, help wanted

#418 Correct stale bot exempt label syntax
  .github/workflows/stale.yml
Labels: infrastructure

#419 Add Azure and Gitlab options
  .github/CONTRIBUTING.md
  README.md
Labels: documentation

#379 add dart support
  .automation/test/dart/README.md
  .automation/test/dart/dart_bad_1.dart
  .automation/test/dart/dart_good_1.dart
  .github/linters/analysis_options.yaml
  Dockerfile
  README.md
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: enhancement, good first issue, help wanted

#420 User gemfile for dependabot and update rubocop
  Dockerfile
  dependencies/Gemfile
  dependencies/Gemfile.lock
Labels: bug

#428 Use Docker instead of run-time build
  action.yml
Labels: performance

#430 BetterRaku
  Dockerfile
Labels: bug, enhancement, performance

#436 Ansible: fix globbing issue and allow .yaml too
  lib/worker.sh
Labels: bug

#437 [tests] Add editor-config tests to the automation
  lib/worker.sh
Labels: automation, enhancement

#435 Adjust handling of docker dependencies
  Dockerfile
Labels: automation

#421 [tests] validate TAP format
  .automation/test/ansible/reports/expected-ANSIBLE.tap
  .automation/test/arm/reports/expected-ARM.tap.ignored
  .automation/test/cfn/reports/expected-CFN.tap
  .automation/test/clojure/reports/expected-CLOJURE.tap.ignored
  .automation/test/coffeescript/reports/expected-COFFEESCRIPT.tap
  .automation/test/css/reports/expected-CSS.tap
  .automation/test/dart/reports/expected-DART.tap
  .automation/test/docker/reports/expected-DOCKER.tap
  .automation/test/env/reports/expected-ENV.tap
  .automation/test/golang/reports/expected-GO.tap.ignored
  .automation/test/html/reports/expected-HTML.tap.ignored
  .automation/test/javascript/reports/expected-JAVASCRIPT_ES.tap
  .automation/test/javascript/reports/expected-JAVASCRIPT_STANDARD.tap
  .automation/test/json/reports/expected-JSON.tap
  .automation/test/kotlin/reports/expected-KOTLIN.tap
  .automation/test/markdown/reports/expected-MARKDOWN.tap
  .automation/test/openapi/reports/expected-OPENAPI.tap
  .automation/test/perl/reports/expected-PERL.tap
  .automation/test/php/reports/expected-PHP.tap
  .automation/test/powershell/reports/expected-POWERSHELL.tap.ignored
  .automation/test/protobuf/reports/expected-PROTOBUF.tap
  .automation/test/python/reports/expected-PYTHON.tap
  .automation/test/raku/reports/expected-RAKU.tap
  .automation/test/ruby/reports/expected-RUBY.tap
  .automation/test/shell/reports/expected-BASH.tap
  .automation/test/terraform/reports/expected-TERRAFORM.tap
  .automation/test/typescript/reports/expected-TYPESCRIPT_ES.tap
  .automation/test/typescript/reports/expected-TYPESCRIPT_STANDARD.tap
  .automation/test/xml/reports/expected-XML.tap
  .automation/test/yml/reports/expected-YML.tap
  .github/workflows/deploy-DEV.yml
  lib/linter.sh
  lib/worker.sh
Labels: automation, enhancement

#448 Fix wrong config on dependabot
  .github/dependabot.yml
Labels: automation

#440 adding abillity to have multi status api checks for visibility
  README.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: enhancement, help wanted

#447 Automerge Dependabot dependencies
  .github/workflows/automerge-dependabot.yml
Labels: automation, dependencies, enhancement

#449 Braces
  .automation/README.md
  .automation/cleanup-docker.sh
  .automation/test/README.md
  .automation/test/ansible/README.md
  .automation/test/ansible/ghe-initialize/templates/ghe-config-apply.sh
  .automation/test/arm/README.md
  .automation/test/cfn/README.md
  .automation/test/clojure/README.md
  .automation/test/coffeescript/README.md
  .automation/test/css/README.md
  .automation/test/dart/README.md
  .automation/test/docker/README.md
  .automation/test/editorconfig-checker/README.md
  .automation/test/env/README.md
  .automation/test/golang/README.md
  .automation/test/html/README.md
  .automation/test/javascript/README.md
  .automation/test/json/README.md
  .automation/test/kotlin/README.md
  .automation/test/markdown/README.md
  .automation/test/openapi/README.md
  .automation/test/perl/README.md
  .automation/test/php/README.md
  .automation/test/powershell/README.md
  .automation/test/python/README.md
  .automation/test/raku/README.md
  .automation/test/ruby/README.md
  .automation/test/shell/README.md
  .automation/test/shell/shell_good_1.sh
  .automation/test/typescript/README.md
  .automation/test/xml/README.md
  .automation/test/yml/README.md
  .automation/upload-docker.sh
  .devcontainer/README.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request-template.md
  .github/workflows/deploy-DEV.yml
  .github/workflows/stack-linter.yml
  .vscode/testlinter.sh
  Dockerfile
  README.md
  TEMPLATES/.powershell-psscriptanalyzer.psd1
  TEMPLATES/README.md
  docs/disabling-linters.md
  docs/run-linter-locally.md
  lib/README.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: Hot Garbage

#452 Add new community maintainers
  .github/CODEOWNERS
Labels: automation

#457 Fix awk
  lib/buildFileList.sh
Labels: bug

#450 State linter
  .automation/test/coffeescript/reports/expected-COFFEESCRIPT.tap.ignored
  .automation/test/states/README.md
  .automation/test/states/reports/expected-STATES.tap.ignored
  .automation/test/states/states_bad_1.json
  .automation/test/states/states_good_1.json
  .github/workflows/stack-linter.yml
  Dockerfile
  README.md
  dependencies/Gemfile.lock
  dependencies/package-lock.json
  dependencies/package.json
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: enhancement

#466 Dart fixes
  Dockerfile
  TEMPLATES/analysis_options.yaml
  docs/disabling-linters.md
  lib/linter.sh
Labels: bug

#463 found the missing link
  .automation/test/cfn/reports/expected-CFN.tap
  .automation/test/cloudformation/README.md
  .automation/test/cloudformation/cloudformation_bad_1.json
  .automation/test/cloudformation/cloudformation_bad_2.yaml
  .automation/test/cloudformation/cloudformation_bad_3.json
  .automation/test/cloudformation/cloudformation_bad_4.yaml
  .automation/test/cloudformation/cloudformation_good_1.json
  .automation/test/cloudformation/cloudformation_good_2.yaml
  .automation/test/cloudformation/cloudformation_good_3.json
  .automation/test/cloudformation/cloudformation_good_4.yaml
  .automation/test/cloudformation/reports/expected-CLOUDFORMATION.tap
  Dockerfile
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: Hot Garbage, enhancement, performance

#469 Adding LFS
  Dockerfile
Labels: enhancement

#470 fix shyaml
  dependencies/Pipfile
  dependencies/Pipfile.lock
  lib/linter.sh
Labels: bug

#415 Adding groovy
  .automation/test/groovy/README.md
  .automation/test/groovy/groovy_bad_01.groovy
  .automation/test/groovy/groovy_good_01.groovy
  .automation/test/json/reports/expected-JSON.tap.ignored
  .github/linters/.groovylintrc.json
  Dockerfile
  README.md
  TEMPLATES/.groovylintrc.json
  dependencies/package.json
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: Stalled

#476 add lua/luacheck to super-linter
  .automation/test/lua/README.md
  .automation/test/lua/lua_bad_1.lua
  .automation/test/lua/lua_good_1.lua
  .github/linters/.luacheckrc
  Dockerfile
  README.md
  TEMPLATES/.luacheckrc
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: enhancement

#455 Python flake8
  .automation/test/python/python_good_1.py
  .github/linters/.flake8
  Dockerfile
  README.md
  TEMPLATES/.flake8
  dependencies/Pipfile
  dependencies/Pipfile.lock
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: enhancement

#477 Add PHPStan support
  .automation/test/php/php_bad_2.php
  .automation/test/php/reports/expected-PHP.tap
  .automation/test/php/reports/expected-PHP_PHPSTAN.tap
  Dockerfile
  README.md
  TEMPLATES/phpstan.neon
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: enhancement

#486 Log
  .automation/cleanup-docker.sh
  .automation/test/ansible/ghe-initialize/templates/ghe-config-apply.sh
  .automation/upload-docker.sh
  Dockerfile
  README.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/log.sh
  lib/termColors.sh
  lib/validation.sh
  lib/worker.sh
Labels: bug, enhancement

#496 Fix yaml
  .automation/test/yaml/README.md
  .automation/test/yaml/reports/expected-YML.tap
  .automation/test/yaml/yml_bad_1.yml
  .automation/test/yaml/yml_good_1.yml
  lib/linter.sh
  lib/worker.sh
Labels: bug

#501 Update linter.sh
  lib/linter.sh
Labels: Hot Garbage, bug
