Repository super-linter/super-linter, pull requests merged in 2020-06, with the labels that each got.

#100 Restructure linter flags
  README.md
  docs/run-linter-locally.md
  lib/linter.sh
Labels: enhancement

#158 Update docs to point to github docker image
  README.md
  docs/run-linter-locally.md
Labels: documentation

#184 update coffeelint
  Dockerfile
  README.md
  docs/disabling-linters.md
Labels: documentation, enhancement

#186 Default workspace
  README.md
  docs/run-linter-locally.md
  lib/linter.sh
Labels: documentation, enhancement

#185 Add stylelint support to super-linter
  .automation/test/css/README.md
  .automation/test/css/css_bad_01.css
  .automation/test/css/css_good_01.css
  .github/linters/.stylelintrc.json
  Dockerfile
  README.md
  TEMPLATES/.stylelintrc.json
  docs/disabling-linters.md
  lib/linter.sh
Labels: documentation, enhancement

#187 fixing docs to point to Docker
  README.md
  TEMPLATES/README.md
Labels: documentation

#196 Up the version
  README.md
Labels: documentation

#202 Add link to wiki for new language support
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#238 Powershell support
  .automation/test/powershell/README.md
  .automation/test/powershell/powershell_bad_1.ps1
  .automation/test/powershell/powershell_bad_1.psd1
  .automation/test/powershell/powershell_bad_1.psm1
  .automation/test/powershell/powershell_good_1.ps1
  .automation/test/powershell/powershell_good_1.psd1
  .automation/test/powershell/powershell_good_1.psm1
  Dockerfile
  README.md
  TEMPLATES/.powershell-psscriptanalyzer.psd1
  lib/linter.sh
Labels: documentation, enhancement

#242 Add support more variants names of env files
  Dockerfile
  lib/linter.sh
Labels: enhancement

#198 More complete release instructions
  .github/CONTRIBUTING.md
Labels: documentation

#258 Release typo
  .github/workflows/deploy-RELEASE.yml
Labels: bug

#263 fixed ansible and powershell
  lib/linter.sh
Labels: bug

#267 Add disclaimer about local development
  README.md
Labels: documentation

#193 Dev: Add Visual Studio Code + Github Codespaces Support
  .devcontainer/devcontainer.json
  .gitattributes
  .vscode/launch.json
  .vscode/testlinter.sh
  README.md
  lib/linter.sh
Labels: enhancement, infrastructure

#256 Clojure lint
  .automation/test/clojure/README.md
  .automation/test/clojure/clojure_bad_1.clj
  .automation/test/clojure/clojure_good_1.clj
  .github/linters/.clj-kondo/config.edn
  .gitignore
  Dockerfile
  README.md
  TEMPLATES/.clj-kondo/config.edn
  docs/disabling-linters.md
  lib/linter.sh
Labels: Do-Not-Merge, documentation, enhancement, help wanted

#287 Remove spell-checker
  .github/actions/spelling/allow/Dockerfile.txt
  .github/actions/spelling/allow/cleanup-docker.sh.txt
  .github/actions/spelling/allow/disabling-linters.md.txt
  .github/actions/spelling/allow/emoji.txt
  .github/actions/spelling/allow/ghe-api-config-apply.yml.txt
  .github/actions/spelling/allow/ghe-config-apply.sh.txt
  .github/actions/spelling/allow/ghe-initial-configuration.yml.txt
  .github/actions/spelling/allow/ghe-ldap-configuration.yml.txt
  .github/actions/spelling/allow/gitignore.txt
  .github/actions/spelling/allow/linter.sh.txt
  .github/actions/spelling/allow/main.yml.txt
  .github/actions/spelling/allow/settings.json.j2.txt
  .github/actions/spelling/allow/words.txt
  .github/actions/spelling/excludes.txt
  .github/actions/spelling/expect.txt
  .github/actions/spelling/patterns.txt
  .github/workflows/check-spelling.yml
Labels: automation

#289 fixed the open Docker issue
  lib/linter.sh
Labels: bug, enhancement

#290 Add step to ensure release is on marketplace
  .github/CONTRIBUTING.md
Labels: documentation

#301 Fix honoring pylint config file
  .github/linters/.python-lint
  TEMPLATES/.python-lint
  lib/linter.sh
Labels: bug

#302 Read Clojure filetypes from $FILE_TYPE, not $FILE
  lib/linter.sh
Labels: bug

#303 Add protolint support to super-linter
  .automation/test/protobuf/README.md
  .automation/test/protobuf/protobuf_bad_1.proto
  .automation/test/protobuf/protobuf_good_1.proto
  .github/linters/.protolintrc.yml
  Dockerfile
  README.md
  TEMPLATES/.protolintrc.yml
  docs/disabling-linters.md
  lib/linter.sh
Labels: documentation, enhancement

#304 Fix vs code debug
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .gitattributes
  .vscode/launch.json
  .vscode/testlinter.sh
  README.md
  lib/linter.sh
Labels: bug, documentation, enhancement

#307 Add actions-tagger workflow to automate version tags
  .github/workflows/versioning.yml
Labels: enhancement

#306 Creating more functions
  lib/README.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/validation.sh
  lib/worker.sh
Labels: enhancement

#308 Update docs to point to v3
  README.md
Labels: documentation

#309 fixed GPR typo
  .automation/upload-docker.sh
Labels: bug

#310 adding logic to deploy major tag versions as well
  .automation/upload-docker.sh
  lib/linter.sh
Labels: automation, bug, enhancement

#319 bump CLJ_KONDO_VERSION
  .automation/upload-docker.sh
  Dockerfile
Labels: bug, enhancement

#327 Better instructions
  docs/disabling-linters.md
Labels: documentation

#328 Don't show shyaml errors to the console
  lib/linter.sh
Labels: bug

#330 DockerFile: Add missing AllUsers Scope when install PSSA
  Dockerfile
Labels: bug, enhancement

#329 Shell check
  .automation/test/ansible/ghe-initialize/templates/ghe-config-apply.sh
  .automation/upload-docker.sh
  .vscode/testlinter.sh
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: automation, bug, enhancement
