Repository super-linter/super-linter, pull requests merged in 2020-10, with the labels that each got.

#818 Fix hadolint
  .github/linters/.hadolint.yml
  Dockerfile
Labels: bug, docker

#819 adding rules
  docs/disabling-linters.md
Labels: documentation

#848 remove cache folder
  lib/buildFileList.sh
  lib/worker.sh
Labels: bug

#846 Adding tekton language support
  .automation/test/tekton/README.md
  .automation/test/tekton/bad/tekton_bad_1.yml
  .automation/test/tekton/good/tekton_good_1.yml
  README.md
  dependencies/package-lock.json
  dependencies/package.json
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/linterVersions.sh
  lib/worker.sh
Labels: docker, documentation, enhancement

#851 add warning:
  lib/buildFileList.sh
Labels: enhancement

#896 update tekton
  dependencies/package-lock.json
  dependencies/package.json
Labels: bug

#903 Add missing dotnet and R dependencies
  Dockerfile
Labels: dependencies, docker
