Repository super-linter/super-linter, pull requests merged in 2020-08, with the labels that each got.

#502 Fix a few typos in the Dart docs
  docs/disabling-linters.md
Labels: documentation

#508 fix default token
  .github/workflows/automerge-dependabot.yml
Labels: automation, bug

#513 no token needed
  .github/workflows/automerge-dependabot.yml
Labels: automation

#478 Support for PHPCS and Psalm
  .automation/test/php/php_bad_2.php
  .automation/test/php/php_good_2.php
  .automation/test/php/reports/expected-PHP_BUILTIN.tap
  .automation/test/php/reports/expected-PHP_PHPCS.tap.ignored
  .automation/test/php/reports/expected-PHP_PHPSTAN.tap
  .automation/test/php/reports/expected-PHP_PSALM.tap.ignored
  Dockerfile
  README.md
  TEMPLATES/phpcs.xml
  TEMPLATES/psalm.xml
  dependencies/phive.xml
  lib/buildFileList.sh
  lib/linter.sh
  lib/possum.sh
  lib/worker.sh
Labels: Ready, enhancement

#516 hadolint...
  .automation/test/docker/good/Dockerfile
  .github/linters/.hadolint.yml
  Dockerfile
  README.md
  TEMPLATES/.hadolint.yml
  docs/disabling-linters.md
  lib/linter.sh
  lib/worker.sh
Labels: docker, documentation, enhancement

#517 Fix Hadolint
  lib/linter.sh
Labels: bug

#519 Fix log function locations in automation
  .automation/cleanup-docker.sh
  .automation/upload-docker.sh
Labels: automation, bug

#522 Fix auto again
  .github/CODEOWNERS
  .github/workflows/automerge-dependabot.yml
Labels: automation, dependencies

#523 Separate maintainer and contributor jobs
  .github/CODEOWNERS
  .github/pull_request-template.md
Labels: infrastructure

#459 Work on adding Java
  .automation/test/java/README.md
  .automation/test/java/java_bad_1.java
  .automation/test/java/java_good_1.java
  .github/linters/sun_checks.xml
  Dockerfile
  README.md
  TEMPLATES/sun_checks.xml
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: Hot Garbage, documentation, enhancement, help wanted

#525 Adding the look
  lib/linter.sh
Labels: bug

#527 Supporting yml and yaml file names
  .github/linters/analysis_options.yml
  TEMPLATES/analysis_options.yml
  docs/disabling-linters.md
  lib/linter.sh
  lib/worker.sh
Labels: Hot Garbage, enhancement

#526 Editorconfig error reporting fix
  lib/linter.sh
Labels: bug

#528 Adding SQL-Lint
  .automation/test/sql/README.md
  .automation/test/sql/sql_bad_1.sql
  .automation/test/sql/sql_good_1.sql
  Dockerfile
  README.md
  dependencies/package-lock.json
  dependencies/package.json
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: docker, enhancement

#529 Adding all codebase scan test
  .automation/clean-code-base-for-tests.sh
  .automation/test/terraform/good/terraform_good_1.tf
  .github/workflows/deploy-DEV.yml
  lib/worker.sh
Labels: Hot Garbage, automation, bug, enhancement, github_actions, performance

#534 PerlCritic basic implementation
  .automation/test/perl/perl_bad_1.pl
  .automation/test/perl/reports/expected-PERL.tap
  .github/linters/.perlcriticrc
  Dockerfile
  README.md
  TEMPLATES/.perlcriticrc
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: documentation, enhancement, good first issue

#546 Fixing Actions job name
  .github/workflows/deploy-DEV-PR.yml
Labels: automation, bug

#545 Add missing editorconfig-checker to linter array
  lib/linter.sh
Labels: bug

#547 Explain GitHub token a bit more
  README.md
Labels: documentation

#548 Only run deploy to Docker on original repo and not forks
  .github/workflows/automerge-dependabot.yml
  .github/workflows/deploy-DEV-PR.yml
  .github/workflows/deploy-PROD.yml
  .github/workflows/deploy-RELEASE.yml
Labels: bug

#553 super slick
  lib/buildFileList.sh
Labels: bug, enhancement

#554 Upgrade npm-groovy-lint@7.2.0 and sql-lint@0.0.15
  .github/linters/.sql-config.json
  TEMPLATES/.sql-config.json
  dependencies/package-lock.json
  dependencies/package.json
  docs/disabling-linters.md
  lib/linter.sh
  lib/worker.sh
Labels: enhancement

#561 smallFix on editorconfig
  lib/linter.sh
Labels: bug

#565 adding more tests and cool logic
  .automation/test/docker/good/Dockerfile.dev
  Dockerfile
  lib/buildFileList.sh
Labels: docker, enhancement

#576 adding more logic
  .github/workflows/automerge-dependabot.yml
Labels: automation

#579 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Hot Garbage

#585 Update CODEOWNERS
  .github/CODEOWNERS
Labels: automation

#586 fix output folder for persistance
  lib/linter.sh
Labels: bug

#587 Push to new GitHub Container Registry
  .automation/upload-docker.sh
Labels: automation

#588 Add LaTeX support
  .automation/test/latex/README.md
  .automation/test/latex/latex_bad_1.tex
  .automation/test/latex/latex_good_1.tex
  .github/linters/.chktexrc
  Dockerfile
  README.md
  TEMPLATES/.chktexrc
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: enhancement

#590 fix logic hole
  lib/linter.sh
Labels: bug

#591 some simple cleanup
  README.md
Labels: documentation

#593 adding black
  .automation/test/python/python_good_1.py
  Dockerfile
  README.md
  dependencies/Pipfile
  dependencies/Pipfile.lock
  docs/disabling-linters.md
  lib/linter.sh
  lib/worker.sh
Labels: documentation, enhancement

#594 Adding better deployment code
  .automation/upload-docker.sh
  .github/workflows/deploy-PROD.yml
  .github/workflows/deploy-RELEASE.yml
  lib/linter.sh
Labels: automation

#609 adding some spaget
  lib/buildFileList.sh
Labels: documentation, enhancement

#611 add quotes
  lib/linter.sh
Labels: bug

#622 Add Stylelint config file
  Dockerfile
  README.md
  lib/linter.sh
Labels: bug, documentation, enhancement

#623 adding hadolint configuration
  Dockerfile
  README.md
  lib/linter.sh
Labels: documentation, enhancement

#624 adding more folders to ignore
  lib/worker.sh
Labels: bug, documentation, enhancement

#625 add file back
  Dockerfile
Labels: bug

#632 Updates to support Terrascan v1.0.0+
  .automation/test/terraform/good/terraform_good_1.tf
  .automation/test/terraform_terrascan/bad/terraform_bad_1.tf
  .automation/test/terraform_terrascan/good/terraform_good_1.tf
  Dockerfile
  README.md
  dependencies/Pipfile
  dependencies/Pipfile.lock
  lib/linter.sh
  lib/worker.sh
Labels: automation, docker, enhancement

#635 Fix Coffeescript
  lib/linter.sh
Labels: bug

#636 better loop
  lib/buildFileList.sh
  lib/linter.sh
Labels: bug

#641 adding bash-exec
  .automation/test/shell/shell_good_1.sh
  Dockerfile
  README.md
  lib/linter.sh
  lib/worker.sh
Labels: docker, enhancement

#615 Adding C# lint
  .automation/test/csharp/README.md
  .automation/test/csharp/csharp_bad_01.cs
  .automation/test/csharp/csharp_good_01.cs
  .automation/test/csharp/reports/expected-CSHARP.tap.ignored
  Dockerfile
  README.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: enhancement

#646 lots of cleanup
  lib/buildFileList.sh
  lib/worker.sh
Labels: bug

#642 Lint shell files with shfmt, fix bash-exec version
  .automation/test/shell_shfmt/.editorconfig
  .automation/test/shell_shfmt/README.md
  .automation/test/shell_shfmt/shell_shfmt_bad_1.sh
  .automation/test/shell_shfmt/shell_shfmt_good_1.sh
  Dockerfile
  README.md
  docs/disabling-linters.md
  lib/buildFileList.sh
  lib/linter.sh
  lib/worker.sh
Labels: bug, enhancement

#647 Update upload-docker.sh
  .automation/upload-docker.sh
Labels: automation
