Repository super-linter/super-linter, pull requests merged in 2021-06, with the labels that each got.

#1602 Add community activity stats
  README.md
Labels: documentation

#1608 wildcard search for ansible
  lib/functions/detectFiles.sh
Labels: bug

#1640 adding find algorithm
  README.md
  lib/functions/buildFileList.sh
  lib/linter.sh
Labels: documentation, enhancement

#1644 adding rules file
  Makefile
  README.md
  TEMPLATES/php.ini
  lib/linter.sh
Labels: enhancement

#1666 Fix README issues
  README.md
Labels: documentation

#1687 Use GitHub Action cache
  .automation/validate-docker-labels.sh
  .github/workflows/deploy-DEV-slim.yml
  .github/workflows/deploy-DEV-standard.yml
  .github/workflows/deploy-PROD-slim.yml
  .github/workflows/deploy-PROD-standard.yml
  .github/workflows/deploy-RELEASE-slim.yml
  .github/workflows/deploy-RELEASE-standard.yml
  Dockerfile
  Dockerfile-slim
Labels: docker, enhancement

#1689 Ignore files marked with @generated marker
  README.md
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/linter.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: documentation, enhancement
