Repository super-linter/super-linter, pull requests merged in 2021-10, with the labels that each got.

#2008 cleaner
  .automation/test/natural_language/README.md
  .automation/test/natural_language/natural_language_bad_01.md
  .automation/test/natural_language/natural_language_good_01.md
  .github/CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  README.md
  TEMPLATES/.textlintrc
  dependencies/package-lock.json
  dependencies/package.json
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/linter.sh
Labels: bug

#2010 switch to main branch
  .automation/README.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/ISSUE.md
  .github/workflows/deploy-DEV-slim.yml
  .github/workflows/deploy-DEV-standard.yml
  .github/workflows/deploy-PROD-slim.yml
  .github/workflows/deploy-PROD-standard.yml
  .github/workflows/deploy-RELEASE-slim.yml
  .github/workflows/deploy-RELEASE-standard.yml
  .github/workflows/draft-release.yml
  .github/workflows/stack-linter.yml
  .github/workflows/trivy.yml
  docs/disabling-linters.md
  docs/using-rules-files.md
  slim/README.md
Labels: infrastructure

#2019 Fix errors by switching to main branch
  .github/workflows/deploy-DEV-slim.yml
  .github/workflows/deploy-DEV-standard.yml
  .github/workflows/stack-linter.yml
Labels: bug

#2020 Trivial fix to README.md
  README.md
Labels: documentation

#2026 Updated README links
  README.md
Labels: documentation

#1911 fix(R linting): try installing the R package before linting R language
  lib/functions/detectFiles.sh
  lib/functions/worker.sh
Labels: enhancement
