Repository super-linter/super-linter, pull requests merged in 2021-07, with the labels that each got.

#1752 move from jsonlint to eslint
  .automation/test/json/json_bad_1.json
  README.md
  dependencies/package-lock.json
  dependencies/package.json
  lib/functions/linterVersions.sh
  lib/linter.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: dependencies, enhancement

#1754 yamllint format
  lib/linter.sh
Labels: bug, enhancement

#1756 cleanup release process
  .automation/update-actions-version.sh
  .github/ISSUE_TEMPLATE/CREATE_RELEASE.md
  .github/workflows/deploy-RELEASE-slim.yml
  .github/workflows/deploy-RELEASE-standard.yml
Labels: automation

#1760 Added support for changing Checkstyle rules file name
  README.md
  lib/linter.sh
Labels: documentation, enhancement

#1764 Minor clang-format linter cleanup
  .automation/test/cpp/README.md
  Dockerfile
  Dockerfile-slim
  README.md
Labels: documentation
