Repository super-linter/super-linter, pull requests merged in 2021-08, with the labels that each got.

#1830 adding black binary
  Dockerfile
  Dockerfile-slim
  dependencies/Pipfile
  dependencies/Pipfile.lock
Labels: dependencies

#1872 Editorial: linked the example `linter.yml` file, added example form that file
  README.md
Labels: documentation

#1890 fixed go issues
  .github/linters/.golangci.yml
  TEMPLATES/.golangci.yml
Labels: bug
