Repository super-linter/super-linter, pull requests merged in 2021-12, with the labels that each got.

#2204 fix default value name for JAVA_FILE_NAME
  README.md
Labels: documentation

#2202 Install R directly and don't report npm-groovy-lint usage stats
  .github/linters/.groovylintrc.json
  Dockerfile
  Dockerfile-slim
  lib/linter.sh
Labels: bug, automation

#2215 Add RUST_2021 test and fix RUST_2021 file list
  .automation/test/rust_2021/rust_bad_1.rs
  .automation/test/rust_2021/rust_good_1.rs
  lib/functions/buildFileList.sh
Labels: bug

#2201 Remove unused stale bot configuration and point to the right label
  .github/stale.yml
  .github/workflows/stale.yml
Labels: infrastructure, automation

#2195 Uninstall Dockerfilelint
  Dockerfile
  Dockerfile-slim
  README.md
  TEMPLATES/.dockerfilelintrc
  dependencies/package-lock.json
  dependencies/package.json
  lib/functions/buildFileList.sh
  lib/linter.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: enhancement, breaking, dependencies

#2218 Updating docs link in the template
  README.md
  TEMPLATES/linter.yml
Labels: documentation

#2180 Lint the whole code base with JSCPD
  README.md
  lib/functions/buildFileList.sh
  lib/linter.sh
Labels: enhancement

#2178 Reduce duplication using a single Dockerfile
  .github/workflows/deploy-DEV-slim.yml
  .github/workflows/deploy-DEV-standard.yml
  .github/workflows/deploy-PROD-slim.yml
  .github/workflows/deploy-PROD-standard.yml
  .github/workflows/deploy-RELEASE-slim.yml
  .github/workflows/deploy-RELEASE-standard.yml
  Dockerfile
  Dockerfile-slim
  lib/functions/linterVersions.sh
Labels: automation, docker
