Repository super-linter/super-linter, pull requests merged in 2022-03, with the labels that each got.

#2575 Echo output only when necessary
  lib/functions/worker.sh
Labels: enhancement

#2580 Don't populate FILE_ARRAY_JSCPD with single files when scanning the whole codebase
  README.md
  lib/functions/buildFileList.sh
Labels: enhancement

#2612 Check for kind when detecting Kubernetes files
  lib/functions/detectFiles.sh
Labels: bug

#2576 Lint the whole Ansible directory
  .automation/test/ansible/README.md
  .automation/test/ansible/ansible_bad_1.yml
  .automation/test/ansible/ansible_good_1.yml
  .automation/test/ansible/inventory/hosts.yml
  .automation/test/ansible/playbooks/ansible_good_1.yml
  .automation/test/ansible/requirements.yml
  .automation/test/ansible/roles/ghe_initialize/defaults/main.yml
  .automation/test/ansible/roles/ghe_initialize/files/ghe-initial-config.json
  .automation/test/ansible/roles/ghe_initialize/files/ghe-license.ghl
  .automation/test/ansible/roles/ghe_initialize/handlers/main.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/collectd-settings.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/ghe-api-config-apply.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/ghe-config-apply.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/ghe-initial-configuration.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/ghe-ldap-configuration.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/main.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/splunk-settings.yml
  .automation/test/ansible/roles/ghe_initialize/templates/collectd-settings.json.j2
  .automation/test/ansible/roles/ghe_initialize/templates/forwarding.conf.j2
  .automation/test/ansible/roles/ghe_initialize/templates/ghe-config-apply.sh
  .automation/test/ansible/roles/ghe_initialize/templates/ldap-settings.json.j2
  .automation/test/ansible/roles/ghe_initialize/templates/settings.json.j2
  .automation/test/ansible/roles/ghe_initialize/templates/splunk-settings.json.j2
  .github/linters/.ansible-lint.yml
  README.md
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: documentation, enhancement, breaking

#2639 Add parameter env to step Update deployment status
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-release.yml
Labels: bug

#2643 Don't override the PATH when installing Psalm
  lib/functions/detectFiles.sh
Labels: bug

#2668 Fix Ansible tests
  .automation/test/ansible/roles/ghe_initialize/handlers/main.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/collectd-settings.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/ghe-api-config-apply.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/ghe-config-apply.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/ghe-initial-configuration.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/ghe-ldap-configuration.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/main.yml
  .automation/test/ansible/roles/ghe_initialize/tasks/splunk-settings.yml
Labels: bug
