Repository super-linter/super-linter, pull requests merged in 2022-05, with the labels that each got.

#2869 Bump textlint-rule-terminology from 2.1.5 to 3.0.0 in /dependencies
  dependencies/package-lock.json
  dependencies/package.json
Labels: dependencies

#2959 adding log level
  lib/functions/detectFiles.sh
Labels: bug, enhancement

#2963 4.9.4
  action.yml
  slim/action.yml
Labels: Release
