Repository super-linter/super-linter, pull requests merged in 2022-01, with the labels that each got.

#2252 Add protolint config
  README.md
  lib/linter.sh
Labels: documentation, enhancement

#2296 Update additional scala extensions
  .github/dependabot.yml
  .github/linters/.cfnlintrc.yml
  .github/linters/.eslintrc.yml
  .github/linters/.golangci.yml
  .github/linters/.protolintrc.yml
  .github/linters/.yaml-lint.yml
  .github/release-drafter.yml
  .github/workflows/deploy-DEV-slim.yml
  .github/workflows/stack-linter.yml
  TEMPLATES/.cfnlintrc.yml
  TEMPLATES/.eslintrc.yml
  TEMPLATES/.golangci.yml
  TEMPLATES/.protolintrc.yml
  lib/functions/buildFileList.sh
Labels: enhancement

#2294 Use Virtual Environment for Python Deps
  Dockerfile
  dependencies/Pipfile
  dependencies/Pipfile.lock
  dependencies/python/ansible-lint/requirements.txt
  dependencies/python/black/requirements.txt
  dependencies/python/build-venvs.sh
  dependencies/python/cfn-lint/requirements.txt
  dependencies/python/cpplint/requirements.txt
  dependencies/python/flake8/requirements.txt
  dependencies/python/isort/requirements.txt
  dependencies/python/mypy/requirements.txt
  dependencies/python/packages.txt
  dependencies/python/pylint/requirements.txt
  dependencies/python/snakefmt/requirements.txt
  dependencies/python/snakemake/requirements.txt
  dependencies/python/sqlfluff/requirements.txt
  dependencies/python/yamllint/requirements.txt
  dependencies/python/yq/requirements.txt
  test/inspec/super-linter/controls/super_linter.rb
Labels: automation, dependencies

#2360 adding perl and python
  lib/functions/detectFiles.sh
Labels: enhancement

#2220 De-duplicate workflows
  .github/workflows/HOLDING/automerge-dependabot.yml.hold
  .github/workflows/deploy-DEV-slim.yml
  .github/workflows/deploy-DEV-standard.yml
  .github/workflows/deploy-PROD-slim.yml
  .github/workflows/deploy-PROD-standard.yml
  .github/workflows/deploy-Production.yml
  .github/workflows/deploy-RELEASE-slim.yml
  .github/workflows/deploy-Release.yml
  Makefile
Labels: infrastructure, automation

#2397 adding flag for error on warning
  README.md
  lib/linter.sh
Labels: bug

#2399 adding lind command output to success
  lib/functions/worker.sh
Labels: enhancement
