Repository super-linter/super-linter, pull requests merged in 2022-09, with the labels that each got.

#3350 Change directory to ANSIBLE_DIRECTORY before running ansible-lint and enable autodetection
  README.md
  lib/functions/worker.sh
  lib/linter.sh
Labels: bug

#3357 Fix issues in the build workflow
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-release.yml
  .github/workflows/repo-visualization.yml
  .github/workflows/trivy.yml
  Dockerfile
  README.md
  dependencies/sgerrand.rsa.pub
Labels: automation, O: backlog 🤖, github_actions

#3351 Add examples for using a shared env file and related STRTA scripts
  docs/run-linter-locally.md
Labels: documentation

#3367 Build process improvements
  .editorconfig
  Dockerfile
  dependencies/package-lock.json
  dependencies/package.json
  lib/functions/linterVersions.sh
  lib/linter.sh
  test/inspec/inspec.lock
  test/inspec/super-linter/controls/super_linter.rb
Labels: performance, automation, dependencies, docker

#3373 Remove non-working cauldron report
  README.md
Labels: infrastructure

#3375 Update release instructions with details about Git tags
  docs/release-process.md
Labels: documentation

#3382 Checkout code before tagging
  .github/workflows/deploy-release.yml
Labels: automation
