Repository super-linter/super-linter, pull requests merged in 2023-11, with the labels that each got.

#4826 update GitHub SSH fingerprints
  lib/functions/setupSSH.sh
Labels: bug

#4821 Change WORKDIR in script, not relying on docker run -w by user
  lib/linter.sh
Labels: enhancement, O: backlog 🤖

#4848 Update google java format and JDK
  .github/linters/.lintr
  Dockerfile
  test/inspec/super-linter/controls/super_linter.rb
Labels: enhancement

#4867 Fixes Regex to match only container files more strictly
  lib/functions/buildFileList.sh
Labels: bug

#4849 Allow to overwrite `PHP_PHPCS_FILE_NAME` value
  README.md
  lib/linter.sh
Labels: enhancement

#4888 Address pwsh install failure
  scripts/install-pwsh.sh
Labels: bug

#4896 Update spectral dependency id
  dependencies/package-lock.json
  dependencies/package.json
  test/inspec/super-linter/controls/super_linter.rb
Labels: dependencies, javascript

#4891 Automatically handle Java dependencies updates
  .github/dependabot.yml
  Dockerfile
  dependencies/checkstyle/build.gradle
  dependencies/google-java-format/build.gradle
  scripts/install-checkstyle.sh
  scripts/install-google-java-format.sh
Labels: infrastructure, O: backlog 🤖

#4894 Refactor issue templates to use forms
  .github/ISSUE_TEMPLATE/BLANK.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT-REQUEST.md
  .github/ISSUE_TEMPLATE/ISSUE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/general-question.md
  docs/run-linter-locally.md
Labels: documentation, infrastructure
