Repository super-linter/super-linter, pull requests merged in 2023-05, with the labels that each got.

#4189 Moves notice under h1
  README.md
Labels: bug

#4202 Fix badging in the README
  README.md
Labels: bug

#4185 Fix syntax error in scripts of `actions/github-script` GHA
  .github/workflows/cd.yml
  .github/workflows/release.yml
Labels: bug, github_actions

#4153 fix: Correct typo in env. var. name
  lib/functions/buildFileList.sh
Labels: bug

#4107 Issue hint when failing to switch back to branch
  lib/functions/buildFileList.sh
Labels: infrastructure

#4225 Removes dependency workflows
  .github/workflows/deps-npm.yml
  .github/workflows/deps-python.yml
Labels: automation

#4274 Fixes bare URL in Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#4312 change ghcr to super-linter/super-linter
  .github/workflows/cd.yml
Labels: automation
