Repository super-linter/super-linter, pull requests merged in 2023-12, with the labels that each got.

#4931 Remove empty title from issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: bug, O: backlog 🤖

#4932 Fix ts-standard configuration
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  README.md
  TEMPLATES/tsconfig.json
  lib/functions/linterRules.sh
  lib/linter.sh
Labels: bug, O: backlog 🤖

#4889 Exit on errors when running Git
  .automation/validate-docker-labels.sh
  .github/workflows/ci.yml
  docs/run-linter-locally.md
  lib/README.md
  lib/functions/buildFileList.sh
  lib/functions/validation.sh
  lib/linter.sh
Labels: bug, breaking, O: backlog 🤖

#4934 Don't write colors and logs on disk if not necessary
  .github/workflows/ci.yml
  README.md
  lib/functions/log.sh
  lib/linter.sh
Labels: enhancement

#4948 Update Maintainer and authors
  Dockerfile
Labels: documentation

#4933 Change directory when checking ignored files
  lib/functions/buildFileList.sh
Labels: bug, O: backlog 🤖

#4926 Validate container image labels
  .automation/README.md
  .automation/clean-code-base-for-tests.sh
  .automation/cleanup-docker.sh
  .automation/upload-docker.sh
  .automation/validate-docker-labels.sh
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Makefile
  docs/run-linter-locally.md
  test/runTests.sh
  test/validate-docker-labels.sh
Labels: infrastructure, O: backlog 🤖

#4953 Don't forcefully validate Git repos if not needed
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Makefile
  lib/functions/log.sh
  lib/functions/validation.sh
  lib/linter.sh
Labels: bug, O: backlog 🤖

#4981 Update documentation
  .github/CONTRIBUTING.md
  README.md
  SECURITY.md
  TEMPLATES/linter.yml
  docs/disabling-linters.md
  docs/run-linter-locally.md
  docs/using-rules-files.md
  test/inspec/super-linter/controls/super_linter.rb
Labels: documentation

#4957 Move instructions from the wiki to docs
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/linters/.sqlfluff
  TEMPLATES/.sqlfluff
  TEMPLATES/phpcs.xml
  docs/add-new-linter.md
  docs/release-process.md
  slim/README.md
Labels: documentation, O: backlog 🤖

#4982 Reduce duplication in CI and CD workflows
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  Makefile
  README.md
  docs/run-linter-locally.md
  lib/linter.sh
Labels: infrastructure

#4961 Group log output on GitHub Actions
  Makefile
  README.md
  lib/functions/log.sh
  lib/linter.sh
Labels: enhancement

#4958 Simplify multi status checks
  lib/linter.sh
Labels: infrastructure, O: backlog 🤖

#4988 Populate the cache with the latest image
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: infrastructure, automation, O: backlog 🤖

#4990 Switch to tflint image because tflint-bundle is deprecated
  .github/linters/.tflint.hcl
  Dockerfile
  TEMPLATES/.tflint.hcl
  lib/functions/detectFiles.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: enhancement, O: backlog 🤖

#4962 Simplify container image build
  .github/CODEOWNERS
  .github/workflows/cd.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  dependencies/phive.xml
  scripts/install-arm-ttk.sh
  scripts/install-checkstyle.sh
  scripts/install-dart-sdk.sh
  scripts/install-glibc.sh
  scripts/install-google-java-format.sh
  scripts/install-ktlint.sh
  scripts/install-lua.sh
  scripts/install-phive.sh
  scripts/install-pwsh.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: infrastructure, O: backlog 🤖

#4984 Lint Go modules
  README.md
  lib/functions/buildFileList.sh
  lib/functions/log.sh
  lib/functions/validation.sh
  lib/functions/worker.sh
  lib/linter.sh
  test/linters/go_modules/go_modules_bad/go.mod
  test/linters/go_modules/go_modules_bad/go.sum
  test/linters/go_modules/go_modules_bad/golang_bad_01.go
  test/linters/go_modules/go_modules_good/go.mod
  test/linters/go_modules/go_modules_good/go.sum
  test/linters/go_modules/go_modules_good/golang_good_01.go
Labels: enhancement, O: backlog 🤖

#4965 Validate local git repo when ignoring files
  lib/linter.sh
Labels: enhancement, O: backlog 🤖

#4995 Don't update the deployment if we didn't start it
  .github/workflows/cd.yml
Labels: automation, O: backlog 🤖

#5026 ci: don't validate dependabot commits
  .github/linters/commitlint.config.js
Labels: automation

#5016 Configure release-please
  .github/linters/.jscpd.json
  .github/release-drafter.yml
  .github/release-please/.release-please-manifest.json
  .github/release-please/release-please-config.json
  .github/workflows/cd.yml
  .github/workflows/draft-release.yml
  .github/workflows/release.yml
  Makefile
  README.md
  action.yml
  docs/release-process.md
  slim/action.yml
Labels: automation, O: backlog 🤖

#5030 ci: fix release workflow
  .github/release-please/.release-please-manifest.json
  .github/release-please/release-please-config.json
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: automation, O: backlog 🤖

#5031 Set current version to 5.7.2
  .github/release-please/.release-please-manifest.json
  .github/workflows/cd.yml
Labels: automation, O: backlog 🤖

#5032 Fix build cache in the cd workflow
  .github/workflows/cd.yml
Labels: automation, O: backlog 🤖

#5033 Use a base image and simplify environments
  .github/release-please/release-please-config.json
  .github/workflows/cd.yml
  Dockerfile
Labels: automation, O: backlog 🤖

#5035 Update prefix for dependency updates
  .github/dependabot.yml
Labels: automation

#5039 ci: configure release-please dry-run and changelog
  .github/release-please/release-please-config.json
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
  README.md
  action.yml
  dev-dependencies/Dockerfile
  dev-dependencies/package-lock.json
  dev-dependencies/package.json
  docs/release-process.md
  slim/action.yml
  version.txt
Labels: automation, O: backlog 🤖

#4994 Simplify lintr installation
  Dockerfile
  lib/functions/detectFiles.sh
  scripts/install-lintr.sh
  scripts/install-r-package-or-fail.R
  test/inspec/super-linter/controls/super_linter.rb
Labels: bug, O: backlog 🤖

#5040 Redact gitleaks secrets from output
  lib/linter.sh
Labels: enhancement, O: backlog 🤖

#4925 Add support for Checkov
  .github/linters/.checkov-test-linters.yaml
  .github/linters/.checkov.baseline
  .github/linters/.checkov.yaml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint-commit.yaml
  .github/workflows/stale.yml
  Dockerfile
  Makefile
  README.md
  action.yml
  dependencies/python/checkov.txt
  dev-dependencies/Dockerfile
  lib/functions/buildFileList.sh
  lib/functions/validation.sh
  lib/linter.sh
  slim/action.yml
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/checkov/bad/terraform_checkov_bad_1.tf
  test/linters/checkov/good/terraform_checkov_good_1.tf
Labels: enhancement, O: backlog 🤖

#5044 Fix file list diff when looking for changes
  Makefile
  lib/functions/buildFileList.sh
  lib/linter.sh
  test/lib/buildFileListTest.sh
Labels: bug, O: backlog 🤖

#5049 feat: automatically handle ktlint updates
  .github/dependabot.yml
  Dockerfile
  dependencies/ktlint/build.gradle
  scripts/install-ktlint.sh
Labels: automation, O: backlog 🤖, dependencies, java

#5063 Enable auto-merge for dependabot pull requests
  .github/workflows/dependabot-automation.yaml
Labels: automation, O: backlog 🤖

#5045 Validate configuration when using USE_FIND_ALGORITHM and VALIDATE_ALL_CODEBASE
  docs/upgrade-guide.md
  lib/functions/validation.sh
Labels: enhancement, breaking, O: backlog 🤖

#5064 Install clj-kondo from its container image
  Dockerfile
  scripts/install-clj-kondo.sh
Labels: O: backlog 🤖, dependencies, docker

#5065 Update Dart, dart analyzer to 3.2.4
  Dockerfile
  TEMPLATES/analysis_options.yml
  docs/upgrade-guide.md
  lib/linter.sh
  scripts/install-dart-sdk.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/dart/dart_bad_1.dart
  test/linters/dart/dart_good_1.dart
Labels: breaking, O: backlog 🤖, dependencies, docker

#5047 Install .NET LTS instead of STS
  scripts/install-dotnet.sh
Labels: O: backlog 🤖, dependencies

#5072 Reduce container image size
  Dockerfile
  dependencies/python/build-venvs.sh
  scripts/clippy.sh
  scripts/install-dotnet.sh
  scripts/install-glibc.sh
  scripts/install-lintr.sh
  scripts/install-lua.sh
  scripts/install-phive.sh
  scripts/install-rustfmt.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: enhancement, O: backlog 🤖

#5074 Install chktex directly
  Dockerfile
  scripts/install-chktex.sh
Labels: enhancement, O: backlog 🤖

#5076 Fail when validating as expected
  lib/functions/validation.sh
Labels: bug
