Repository super-linter/super-linter, pull requests merged in 2023-06, with the labels that each got.

#4348 git check-ignore is run on every file
  lib/functions/buildFileList.sh
Labels: bug, O: backlog 🤖

#4375 Update Kubernetes File Detection
  lib/functions/detectFiles.sh
Labels: bug

#4351 Running superlinter as a user not defined in /etc/passwd causes error messages
  lib/functions/validation.sh
Labels: bug

#4347 4028: Use a script to install clj-kondo
  Dockerfile
  scripts/install-clj-kondo.sh
Labels: infrastructure
