Repository super-linter/super-linter, pull requests merged in 2023-01, with the labels that each got.

#3657 Update go modules in test to resolve security issues
  .automation/test/go.mod
  .automation/test/go.sum
Labels: automation, O: backlog 🤖

#3556 Use git check-ignore instead of a (incomplete) list of ignored files
  lib/functions/buildFileList.sh
Labels: O: backlog 🤖

#3788 Don't show Gitleaks banner and Ansible-lint verbose output in output to make it more concise
  lib/linter.sh
Labels: enhancement, O: backlog 🤖

#3517 add jenkinsfile to groovy files
  lib/functions/buildFileList.sh
Labels: enhancement, O: backlog 🤖

#3811 Validate if we the test suite runs both good and bad tests
  .github/linters/.ansible-lint.yml
  lib/functions/worker.sh
Labels: enhancement
