Repository super-linter/super-linter, pull requests merged in 2023-07, with the labels that each got.

#4393 Update README.md
  README.md
Labels: documentation

#4441 Use calculated major version instead of hardcoded v5
  .github/workflows/release.yml
Labels: automation

#4422 Improve GITHUB_DOMAIN/GITHUB_SERVER_URL default value handling
  lib/linter.sh
Labels: enhancement

#4449 Fix typo in CD pipeline
  .github/workflows/cd.yml
Labels: bug

#4451 Handle tflint deprecations
  lib/functions/worker.sh
Labels: dependencies

#4497 Bumps PyYAML to 6.0.1
  dependencies/python/ansible-lint.txt
  dependencies/python/cfn-lint.txt
  dependencies/python/snakemake.txt
  dependencies/python/sqlfluff.txt
  dependencies/python/yamllint.txt
  dependencies/python/yq.txt
Labels: dependencies
