Repository super-linter/super-linter, pull requests merged in 2023-08, with the labels that each got.

#4446 Add dependencies for Next (node), React (node), and Standard (ruby)
  dependencies/Gemfile
  dependencies/Gemfile.lock
  dependencies/package-lock.json
  dependencies/package.json
Labels: dependencies

#4505 Update docker image used by slim version of the action
  slim/action.yml
Labels: automation

#4538 Fix typo on .markdown-lint.yml
  TEMPLATES/.markdown-lint.yml
Labels: documentation

#4524 Add `cmake` to Dockerfile dependencies
  Dockerfile
Labels: dependencies

#4563 Changing DEFAULT_BRANCH in README to main
  README.md
Labels: documentation

#4565 Use latest major slim version
  slim/action.yml
Labels: automation

#4543 Follow up with several more documentation and automation renames for the org move from github to super-linter
  .automation/cleanup-docker.sh
  .automation/test/go.mod
  .automation/validate-docker-labels.sh
  .devcontainer/devcontainer.json
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/release-drafter.yml
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  README.md
  TEMPLATES/linter.yml
  action.yml
  docs/disabling-linters.md
  docs/release-process.md
  docs/run-linter-locally.md
  lib/functions/buildFileList.sh
  lib/linter.sh
  slim/README.md
  slim/action.yml
Labels: documentation, automation

#4589 Specify ghcr.io for docker location
  docs/run-linter-locally.md
Labels: documentation

#4579 fix: Move commands to correct place
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  scripts/install-lintr.sh
  scripts/install-lua.sh
Labels: bug

#4567 Fix docker image name in docs
  docs/run-linter-locally.md
Labels: documentation, automation
