Repository super-linter/super-linter, pull requests merged in 2023-04, with the labels that each got.

#3501 R fix dependency installation
  lib/functions/detectFiles.sh
Labels: bug, O: backlog 🤖

#4059 fix: updating actionlint to latest version v1.6.24
  Dockerfile
Labels: dependencies, docker

#3609 Textlint should check every file
  lib/functions/buildFileList.sh
Labels: enhancement, O: backlog 🤖
