Repository super-linter/super-linter, pull requests merged in 2023-10, with the labels that each got.

#4715 Fix image name in run-linter-locally.md
  docs/run-linter-locally.md
Labels: documentation

#4718 Update go version of go.mod
  .automation/test/go.mod
Labels: dependencies

#4737 Remove codecov reports
  .github/workflows/ci.yml
  README.md
Labels: automation

#4627 feat: use built-in `dotnet format` linter for csharp language
  .automation/test/csharp/csharp_good_02.cs
  README.md
  lib/linter.sh
  scripts/install-dotnet.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: infrastructure, O: backlog 🤖

#4761 Revert exact version pinning
  .github/workflows/release.yml
Labels: automation

#4772 Run tests against the production image
  .github/workflows/cd.yml
Labels: infrastructure, automation, github_actions

#4775 Create thank_contributors.yaml
  .github/workflows/thank_contributors.yaml
Labels: automation

#4778 Use the same image tags in CI and CD
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Makefile
  docs/run-linter-locally.md
Labels: infrastructure, automation, O: backlog 🤖

#4773 Fix target key in CD workflow
  .github/workflows/cd.yml
Labels: bug, infrastructure, automation, O: backlog 🤖, github_actions

#4795 Update README: replace ansible-lint configuration link
  README.md
Labels: documentation

#4796 Simplify pip requirements files
  .github/scripts/update-npm.sh
  .github/scripts/update-python.sh
  dependencies/python/ansible-lint.txt
  dependencies/python/black.txt
  dependencies/python/build-venvs.sh
  dependencies/python/cfn-lint.txt
  dependencies/python/flake8.txt
  dependencies/python/mypy.txt
  dependencies/python/pylint.txt
  dependencies/python/snakefmt.txt
  dependencies/python/snakemake.txt
  dependencies/python/sqlfluff.txt
  dependencies/python/yamllint.txt
  dependencies/python/yq.txt
Labels: O: backlog 🤖, dependencies, python

#4088 Batched & parallel support for cfn-lint, eslint, gitleaks
  Dockerfile
  README.md
  lib/functions/experimental-batch-workers/README.md
  lib/functions/experimental-batch-workers/base.sh
  lib/functions/experimental-batch-workers/cfn-lint.sh
  lib/functions/experimental-batch-workers/eslint.sh
  lib/functions/experimental-batch-workers/gitleaks.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: enhancement, performance, O: backlog 🤖
