Repository super-linter/super-linter, pull requests merged in 2023-09, with the labels that each got.

#4592 Update chktex docker image
  .automation/test/latex/latex_good_1.tex
  Dockerfile
Labels: dependencies

#4643 Add renovate-config-validator
  .automation/test/renovate/.renovaterc_bad_03.json
  .automation/test/renovate/.renovaterc_bad_04.json5
  .automation/test/renovate/.renovaterc_good_03.json
  .automation/test/renovate/.renovaterc_good_04.json5
  .automation/test/renovate/README.md
  .automation/test/renovate/renovate_bad_01.json
  .automation/test/renovate/renovate_bad_02.json5
  .automation/test/renovate/renovate_good_01.json
  .automation/test/renovate/renovate_good_02.json5
  README.md
  dependencies/package-lock.json
  dependencies/package.json
  lib/functions/buildFileList.sh
  lib/functions/linterVersions.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: enhancement

#4648 Configure automation for dependency updates
  .github/workflows/dependabot-automation.yaml
Labels: infrastructure, automation, O: backlog 🤖

#4644 use checkout v4 in README
  README.md
  docs/run-linter-locally.md
Labels: documentation

#4655 Put dependency updates in the maintenance section by default
  .github/release-drafter.yml
Labels: automation

#4654 Remove notice from april availability issue
  README.md
Labels: documentation

#4470 Add exception for type-linting
  .github/linters/tsconfig.json
Labels: bug, O: backlog 🤖

#4653 Add Babel preset for React package
  dependencies/package-lock.json
  dependencies/package.json
  test/inspec/super-linter/controls/super_linter.rb
Labels: dependencies

#4677 Update golang to 1.21.1
  Dockerfile
Labels: enhancement

#4674 renovate-config-validator: validate shareable config preset
  .automation/test/renovate/README.md
  .automation/test/renovate/bad/.renovaterc.json
  .automation/test/renovate/bad/.renovaterc.json5
  .automation/test/renovate/bad/default.json
  .automation/test/renovate/bad/hoge.json
  .automation/test/renovate/bad/renovate.json
  .automation/test/renovate/bad/renovate.json5
  .automation/test/renovate/good/.renovaterc.json
  .automation/test/renovate/good/.renovaterc.json5
  .automation/test/renovate/good/default.json
  .automation/test/renovate/good/hoge.json
  .automation/test/renovate/good/renovate.json
  .automation/test/renovate/good/renovate.json5
  .github/workflows/ci.yml
  README.md
  lib/functions/buildFileList.sh
  lib/functions/worker.sh
Labels: enhancement, O: backlog 🤖
