Repository super-linter/super-linter, pull requests merged in 2024-08, with the labels that each got.

#5948 docs: add info about standard and prettier
  docs/upgrade-guide.md
  lib/functions/validation.sh
Labels: documentation, O: backlog 🤖

#5949 fix: define private output dir before using it
  lib/linter.sh
Labels: bug, O: backlog 🤖

#5950 fix: adjust previous commit id on merge commits
  Makefile
  lib/linter.sh
  test/data/github-event/github-event-push-merge-commit.json
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#5953 chore: remove clippy script, run clippy directly
  .gitignore
  Dockerfile
  lib/functions/linterCommands.sh
  lib/functions/worker.sh
  scripts/clippy.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: infrastructure, O: backlog 🤖

#5946 chore: move rules vars to a dedicated file
  Makefile
  docs/add-new-linter.md
  lib/globals/languages.sh
  lib/globals/linterRules.sh
  lib/linter.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/buildFileListTest.sh
  test/lib/linterRulesTest.sh
Labels: infrastructure, O: backlog 🤖

#5957 chore: add linter commands tests
  Makefile
  test/lib/linterCommandsTest.sh
Labels: infrastructure, O: backlog 🤖

#5958 feat: support ignore_gitignored_files with jscpd
  docs/upgrade-guide.md
  lib/functions/linterCommands.sh
  test/lib/linterCommandsTest.sh
Labels: enhancement, O: backlog 🤖

#5959 README: fix typos
  README.md
Labels: documentation, O: backlog 🤖

#5981 chore: add tests for linter rules path corner cases
  test/lib/linterRulesTest.sh
Labels: infrastructure, O: backlog 🤖

#5982 fix: add missing rspec dependencies
  dependencies/Gemfile
  dependencies/Gemfile.lock
  test/inspec/super-linter/controls/super_linter.rb
Labels: bug, O: backlog 🤖

#5978 feat: local fix mode
  .gitignore
  Makefile
  README.md
  docs/add-new-linter.md
  docs/run-linter-locally.md
  docs/upgrade-guide.md
  lib/functions/linterCommands.sh
  lib/functions/validation.sh
  lib/functions/worker.sh
  lib/globals/linterCommandsOptions.sh
  lib/linter.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/linterCommandsTest.sh
  test/lib/validationTest.sh
  test/linters/groovy/groovy_good_01.groovy
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: enhancement, O: backlog 🤖

#5984 chore: mount the whole lib dir in the devcontainer
  .devcontainer/devcontainer.json
Labels: infrastructure, O: backlog 🤖

#5985 chore: remove h1 from the pr template
  .github/pull_request-template.md
Labels: infrastructure, O: backlog 🤖

#5988 fix: use cargo clippy instead of cargo-clippy
  lib/functions/linterCommands.sh
  scripts/linterVersions.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#5986 fix: add RENOVATE_X_IGNORE_RE2 env var to remove warning
  Dockerfile
  test/inspec/super-linter/controls/super_linter.rb
Labels: bug, O: backlog 🤖

#5987 fix: add missing fix mode options and test cases
  .github/linters/.eslintrc.yml
  .github/linters/.golangci.yml
  .github/linters/.jscpd.json
  Makefile
  README.md
  docs/add-new-linter.md
  lib/functions/validation.sh
  lib/functions/worker.sh
  lib/globals/linterCommandsOptions.sh
  lib/linter.sh
  test/lib/globalsLinterCommandsOptionsTest.sh
  test/lib/linterCommandsTest.sh
  test/lib/linterRulesTest.sh
  test/linters-config/fix-mode/.ansible-lint.yml
  test/linters-config/fix-mode/.eslintrc.yml
  test/linters-config/fix-mode/.golangci.yml
  test/linters/ansible/bad/playbooks/ansible_bad_1.yml
  test/linters/ansible/good/playbooks/ansible_good_1.yml
  test/linters/go/golang_bad_01.go
  test/linters/go_modules/go_modules_bad/golang_bad_01.go
  test/linters/javascript_es/javascript_bad_1.js
  test/linters/javascript_es/javascript_good_1.js
  test/linters/javascript_prettier/javascript_bad_1.js
  test/linters/javascript_standard/javascript_bad_1.js
  test/linters/json/.dotfile_json_bad_2.json
  test/linters/json/json_bad_1.json
  test/linters/jsonc/json_bad_1.jsonc
  test/linters/jsx/jsx_bad_1.jsx
  test/linters/jsx/jsx_good_1.jsx
  test/linters/markdown/markdown_bad_1.md
  test/linters/protobuf/protobuf_bad_1.proto
  test/linters/python_ruff/python_bad_1.py
  test/linters/rust_clippy/bad/src/main.rs
  test/linters/sqlfluff/sqlfluff_bad_1.sql
  test/linters/tsx/tsx_bad_1.tsx
  test/linters/tsx/tsx_good_1.tsx
  test/linters/typescript_es/typescript_bad_1.ts
  test/linters/typescript_prettier/typescript_bad_1.ts
  test/linters/typescript_standard/typescript_bad_1.ts
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: bug, O: backlog 🤖

#5995 chore: remove test leftovers before running fix test
  .github/workflows/ci.yml
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: bug, O: backlog 🤖

#6015 build: fix build metadata
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  scripts/build-metadata.sh
Labels: infrastructure, O: backlog 🤖

#6017 ci: fetch the whole repo when setting build meta
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: infrastructure, O: backlog 🤖

#6016 chore: disable dotnet telemetry
  Dockerfile
  test/inspec/super-linter/controls/super_linter.rb
Labels: infrastructure, O: backlog 🤖

#6024 build: automatically set scalafmt version
  .github/workflows/sync-scala-version.yaml
  Dockerfile
  TEMPLATES/.scalafmt.conf
Labels: infrastructure, O: backlog 🤖

#5993 feat: allow customizing gitleaks log level
  Makefile
  README.md
  lib/functions/linterCommands.sh
  lib/globals/linterCommandsOptions.sh
  test/lib/linterCommandsTest.sh
  test/run-super-linter-tests.sh
Labels: enhancement, O: backlog 🤖

#6018 chore: remove file_array leftovers
  lib/functions/buildFileList.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: infrastructure, O: backlog 🤖

#5991 fix!: remove sql-lint
  README.md
  TEMPLATES/.sql-config.json
  dependencies/package-lock.json
  dependencies/package.json
  docs/upgrade-guide.md
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/functions/validation.sh
  lib/functions/worker.sh
  lib/globals/languages.sh
  lib/globals/linterRules.sh
  scripts/linterVersions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/sql/sql_bad_1.sql
  test/linters/sql/sql_good_1.sql
Labels: bug, breaking, O: backlog 🤖

#6020 fix: remove intro text from stdout and stderr and always create stdout and stderr
  lib/functions/worker.sh
  lib/linter.sh
Labels: bug, breaking, O: backlog 🤖

#6027 fix: avoid concurrent edits to the same file
  lib/functions/validation.sh
  lib/linter.sh
  test/lib/validationTest.sh
Labels: bug, O: backlog 🤖

#6028 chore: fix formatting issues
  .devcontainer/devcontainer.json
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/dependabot.yml
  .github/linters/.checkov-test-linters-failure.yaml
  .github/linters/.checkov-test-linters-success.yaml
  .github/linters/.checkov.yaml
  .github/linters/.eslintrc.yml
  .github/linters/.golangci.yml
  .github/linters/.hadolint.yaml
  .github/linters/.jscpd-test-linters.json
  .github/linters/.jscpd.json
  .github/linters/.markdown-lint.yml
  .github/linters/tsconfig.json
  .github/pull_request-template.md
  .github/release-please/release-please-config.json
  .github/workflows/dependabot-automation.yaml
  .github/workflows/lint-commit.yaml
  .github/workflows/stale.yml
  .github/workflows/thank_contributors.yaml
  .prettierignore
  CODE_OF_CONDUCT.md
  README.md
  TEMPLATES/.ansible-lint.yml
  TEMPLATES/.checkov.yaml
  TEMPLATES/.eslintrc.yml
  TEMPLATES/.groovylintrc.json
  TEMPLATES/.jscpd.json
  TEMPLATES/.markdown-lint.yml
  TEMPLATES/.openapirc.yml
  TEMPLATES/actionlint.yml
  action.yml
  docs/add-new-linter.md
  docs/release-process.md
  docs/run-linter-locally.md
  slim/action.yml
  test/data/github-event/github-event-push.json
  test/linters-config/fix-mode/.ansible-lint.yml
  test/linters-config/fix-mode/.eslintrc.yml
  test/linters-config/fix-mode/.golangci.yml
Labels: infrastructure

#5990 build: run npm audit when installing dependencies
  Dockerfile
  dependencies/package-lock.json
Labels: infrastructure, O: backlog 🤖

#6025 feat: support additional prettier languages
  .github/linters/.jscpd.json
  Makefile
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/globals/languages.sh
  lib/globals/linterCommandsOptions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/lib/globalsLanguagesTest.sh
  test/linters/css_prettier/css_prettier_bad_01.css
  test/linters/css_prettier/css_prettier_good_01.css
  test/linters/graphql_prettier/graphql_prettier_bad_01.graphql
  test/linters/graphql_prettier/graphql_prettier_good_01.graphql
  test/linters/html_prettier/html_prettier_bad_01.html
  test/linters/html_prettier/html_prettier_good_01.html
  test/linters/json_prettier/json_prettier_bad_01.json
  test/linters/json_prettier/json_prettier_good_01.json
  test/linters/jsx_prettier/jsx_prettier_bad_01.jsx
  test/linters/jsx_prettier/jsx_prettier_good_01.jsx
  test/linters/markdown_prettier/markdown_prettier_bad_01.md
  test/linters/markdown_prettier/markdown_prettier_good_01.md
  test/linters/vue_prettier/vue_prettier_bad_01.vue
  test/linters/vue_prettier/vue_prettier_good_01.vue
  test/linters/yaml_prettier/yaml_prettier_bad_01.yml
  test/linters/yaml_prettier/yaml_prettier_bad_02.yaml
  test/linters/yaml_prettier/yaml_prettier_good_01.yml
  test/linters/yaml_prettier/yaml_prettier_good_02.yaml
  test/testUtils.sh
Labels: enhancement, O: backlog 🤖

#6038 docs: update supported linters table
  README.md
Labels: documentation, O: backlog 🤖

#6041 feat: format JSONC and JSON5 with prettier
  README.md
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/globals/languages.sh
  lib/globals/linterCommandsOptions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-standard.md
  test/linters/jsonc_prettier/json_prettier_bad_1.json5
  test/linters/jsonc_prettier/json_prettier_good_1.json5
  test/testUtils.sh
Labels: enhancement, O: backlog 🤖

#6042 chore: configure prettier in the devcontainer
  .devcontainer/devcontainer.json
Labels: infrastructure, O: backlog 🤖

#6059 docs: add details about how jscpd, checkov ignore
  README.md
Labels: documentation, O: backlog 🤖

#6061 chore: update micromatch dependency
  dependencies/package-lock.json
Labels: O: backlog 🤖, security

#6063 chore: format super-linter summaries
  .github/linters/.markdown-lint.yml
  .prettierignore
  Makefile
  lib/functions/output.sh
  lib/linter.sh
  test/data/super-linter-summary/markdown/table/expected-summary-footer-failure.md
  test/data/super-linter-summary/markdown/table/expected-summary-footer-success.md
  test/data/super-linter-summary/markdown/table/expected-summary-heading.md
  test/data/super-linter-summary/markdown/table/expected-summary-line-failure.md
  test/data/super-linter-summary/markdown/table/expected-summary-line-success.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-standard.md
  test/lib/outputTest.sh
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: infrastructure, O: backlog 🤖

#6080 chore: new ignore example and set word wrap
  .devcontainer/devcontainer.json
  README.md
Labels: documentation, infrastructure, O: backlog 🤖

#6083 feat: add pyink as a Python formatter
  .github/linters/.jscpd.json
  Dockerfile
  README.md
  TEMPLATES/.python-pyink
  dependencies/python/pyink.txt
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/globals/languages.sh
  lib/globals/linterCommandsOptions.sh
  lib/globals/linterRules.sh
  scripts/linterVersions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-standard.md
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/python_pyink/python_bad_1.py
  test/linters/python_pyink/python_good_1.py
  test/testUtils.sh
Labels: enhancement, O: backlog 🤖

#6085 fix: correctly load custom linter commands
  .devcontainer/devcontainer.json
  Makefile
  dependencies/package-lock.json
  docs/run-linter-locally.md
  lib/functions/linterCommands.sh
  test/lib/linterCommandsTest.sh
Labels: bug, O: backlog 🤖

#6092 chore: configure terraform formatting
  .devcontainer/devcontainer.json
Labels: infrastructure, O: backlog 🤖

#6094 feat: allow passing custom options to rust clippy
  .devcontainer/devcontainer.json
  Makefile
  README.md
  lib/functions/linterCommands.sh
  test/lib/linterCommandsTest.sh
  test/linters/arm/arm_good_1.json
  test/testUtils.sh
Labels: enhancement, O: backlog 🤖

#6095 feat: optionally remove color codes from output
  .devcontainer/devcontainer.env
  README.md
  lib/functions/output.sh
  lib/functions/validation.sh
  lib/functions/worker.sh
  lib/linter.sh
  test/data/output/ansi-color-codes/super-linter-parallel-stdout-ARM
  test/data/output/ansi-color-codes/super-linter-parallel-stdout-ARM-no-ANSI-color-codes
  test/lib/outputTest.sh
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: enhancement, O: backlog 🤖
