Repository super-linter/super-linter, pull requests merged in 2024-02, with the labels that each got.

#5214 Fail on errors when installing chktex
  scripts/install-chktex.sh
Labels: infrastructure, O: backlog 🤖

#5210 Remove mypy cache
  lib/linter.sh
Labels: enhancement, O: backlog 🤖

#5238 Check if Stdout and Stderr have elements before printing
  .github/workflows/ci.yml
  lib/functions/buildFileList.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: infrastructure, O: backlog 🤖

#5240 Create mypy cache directory
  lib/functions/detectFiles.sh
Labels: bug, O: backlog 🤖

#5242 Automatically set the default branch
  .github/workflows/ci.yml
  README.md
  lib/functions/githubEvent.sh
  lib/linter.sh
  test/lib/githubEventTest.sh
Labels: enhancement, O: backlog 🤖

#5250 Lint xsd files
  lib/functions/buildFileList.sh
  test/linters/xml/xsd_bad_1.xsd
  test/linters/xml/xsd_good_1.xsd
Labels: enhancement, O: backlog 🤖

#5249 Unset the LOG_LEVEL variable
  Makefile
  README.md
  lib/functions/detectFiles.sh
  lib/functions/log.sh
  lib/functions/validation.sh
  lib/linter.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/buildFileListTest.sh
  test/lib/githubEventTest.sh
  test/lib/validationTest.sh
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#5216 Initialize GitHub domain variable
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Makefile
  README.md
  lib/functions/setupSSH.sh
  lib/linter.sh
  test/lib/setupSSHTest.sh
Labels: bug, O: backlog 🤖

#5246 Initialize terrascan at runtime
  Dockerfile
  Makefile
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/terraform_terrascan/good/terraform-terrascan_good_2.tf
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#5245 Install dotnet and powershell from images
  Dockerfile
  scripts/install-dotnet.sh
  scripts/install-pwsh.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: enhancement, O: backlog 🤖

#5251 Show error output when info is disabled
  Makefile
  lib/functions/detectFiles.sh
  lib/functions/worker.sh
  lib/linter.sh
  test/run-super-linter-tests.sh
Labels: enhancement, O: backlog 🤖

#5255 Add a notable features to the readme
  README.md
Labels: documentation, O: backlog 🤖

#5252 Rely on default pylint configuration
  TEMPLATES/.python-lint
Labels: bug, O: backlog 🤖

#5278 Take package-lock into account in dev-container
  .github/dependabot.yml
  dev-dependencies/Dockerfile
Labels: bug, automation, O: backlog 🤖

#5284 Configure git user and email when pushing a new release
  .github/workflows/cd.yml
Labels: bug, O: backlog 🤖

#5291 chore(docs): fix typos in readme
  README.md
Labels: documentation, O: backlog 🤖

#5311 Don't explicitly install typescript eslint parser
  dependencies/package-lock.json
  dependencies/package.json
Labels: O: backlog 🤖, dependencies, javascript

#5288 Fix GitHub Actions debug logging
  .devcontainer/devcontainer.env
  .github/workflows/ci.yml
  Makefile
  README.md
  docs/run-linter-locally.md
  lib/linter.sh
Labels: bug, O: backlog 🤖

#5307 Dynamically build the test matrix
  .github/workflows/ci.yml
Labels: automation, O: backlog 🤖

#5126 Enable shell error checks
  README.md
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/functions/log.sh
  lib/functions/setupSSH.sh
  lib/functions/updateSSL.sh
  lib/functions/validation.sh
  lib/linter.sh
  test/lib/buildFileListTest.sh
  test/lib/githubEventTest.sh
  test/lib/setupSSHTest.sh
  test/lib/validationTest.sh
Labels: enhancement, O: backlog 🤖

#5312 Simplify log infrastructure
  lib/functions/log.sh
  lib/functions/validation.sh
  lib/linter.sh
Labels: bug, O: backlog 🤖

#5319 Fix log level variable assignment
  lib/functions/log.sh
Labels: bug, O: backlog 🤖

#5316 Suggest setting fetch-depth on ref errors
  lib/functions/buildFileList.sh
  lib/functions/validation.sh
Labels: bug, O: backlog 🤖

#5336 Don't immediately exit on errors
  .github/release-please/release-please-config.json
  lib/linter.sh
  scripts/linterVersions.sh
Labels: bug, O: backlog 🤖

#5338 Fix README typo
  README.md
Labels: bug, O: backlog 🤖

#5317 Install zlib from alpine packages
  scripts/install-glibc.sh
Labels: bug, O: backlog 🤖

#5334 Add `glibc` via `gcompat` layer
  Dockerfile
  dependencies/sgerrand.rsa.pub
  scripts/install-glibc.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: infrastructure, O: backlog 🤖
