Repository super-linter/super-linter, pull requests merged in 2024-09, with the labels that each got.

#6113 feat: implement a linter to check git conflicts
  .devcontainer/devcontainer.json
  Dockerfile
  Makefile
  README.md
  docs/add-new-linter.md
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/globals/languages.sh
  scripts/git-merge-conflict-markers.sh
  scripts/linterVersions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/git_merge_conflict_markers/git_merge_conflict_markers_bad_01.txt
  test/linters/git_merge_conflict_markers/git_merge_conflict_markers_bad_02.txt
  test/linters/git_merge_conflict_markers/git_merge_conflict_markers_good_01.txt
  test/linters/git_merge_conflict_markers/git_merge_conflict_markers_good_02.txt
Labels: enhancement, O: backlog 🤖

#6117 docs: update link to jscpd documentation
  docs/upgrade-guide.md
Labels: documentation, O: backlog 🤖

#6139 chore: manage php dependencies
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .gitignore
  Dockerfile
  Makefile
  dependencies/composer/composer.json
  dependencies/composer/composer.lock
  dependencies/phive.xml
  scripts/install-phive.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: infrastructure, O: backlog 🤖

#6119 chore: devcontainer, docs, prettier config
  .devcontainer/devcontainer.json
  .github/CONTRIBUTING.md
  .github/pull_request-template.md
  .github/workflows/ci.yml
  CODE_OF_CONDUCT.md
  Makefile
  README.md
  TEMPLATES/README.md
  docs/add-new-linter.md
  docs/release-process.md
  docs/run-linter-locally.md
  docs/upgrade-guide.md
  prettier.config.js
  test/run-super-linter-tests.sh
Labels: documentation, infrastructure, O: backlog 🤖

#6118 feat: lint commit messages with commitlint
  .github/workflows/lint-commit.yaml
  Makefile
  README.md
  commitlint.config.js
  dependencies/package-lock.json
  dependencies/package.json
  dev-dependencies/Dockerfile
  dev-dependencies/package-lock.json
  dev-dependencies/package.json
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/functions/validation.sh
  lib/globals/languages.sh
  lib/globals/linterCommandsOptions.sh
  lib/linter.sh
  scripts/linterVersions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/linterCommandsTest.sh
  test/lib/validationTest.sh
  test/linters/git_commitlint/.gitignore
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: enhancement, automation, O: backlog 🤖

#6088 docs: Improve ignore/exclude examples
  README.md
Labels: documentation, O: backlog 🤖

#5893 chore: simplified `awk` usage for version extraction
  docs/add-new-linter.md
  scripts/install-checkstyle.sh
  scripts/install-google-java-format.sh
  scripts/install-ktlint.sh
Labels: infrastructure, O: backlog 🤖
