Repository super-linter/super-linter, pull requests merged in 2024-10, with the labels that each got.

#6244 chore: explain how to configure the path
  docs/add-new-linter.md
Labels: documentation, O: backlog 🤖

#6247 chore: group dependency updates prs
  .github/dependabot.yml
  dependencies/composer/composer.json
  dependencies/composer/composer.lock
  docs/add-new-linter.md
Labels: infrastructure, O: backlog 🤖

#6241 chore: Add `.DS_Store` to `.gitignore`
  .gitignore
Labels: infrastructure, O: backlog 🤖

#6176 chore: shorten linter versions
  Makefile
  lib/linter.sh
  scripts/linterVersions.sh
  test/lib/linterVersionsTest.sh
Labels: enhancement, O: backlog 🤖

#6275 chore: add mypy to the python group
  .github/dependabot.yml
Labels: infrastructure, O: backlog 🤖
