Repository super-linter/super-linter, pull requests merged in 2024-06, with the labels that each got.

#5631 Include Helm for checkov scans
  Dockerfile
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/checkov/bad/bad_chart/Chart.yaml
  test/linters/checkov/bad/bad_chart/templates/deployment.yaml
  test/linters/checkov/bad/bad_chart/values.yaml
  test/linters/checkov/good/good_chart/Chart.yaml
  test/linters/checkov/good/good_chart/templates/deployment.yaml
  test/linters/checkov/good/good_chart/values.yaml
Labels: enhancement, O: backlog 🤖

#5788 Update run-linter-locally.md to improve build locally
  docs/run-linter-locally.md
Labels: documentation, O: backlog 🤖

#5790 fix: don't skip processing ansible_directory pwd
  Makefile
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/functions/validation.sh
  lib/linter.sh
  test/lib/buildFileListTest.sh
  test/lib/detectFilesTest.sh
  test/lib/githubEventTest.sh
  test/lib/setupSSHTest.sh
  test/lib/validationTest.sh
Labels: bug, O: backlog 🤖

#5792 feat: configure github server url
  README.md
  lib/functions/githubDomain.sh
  lib/functions/validation.sh
  lib/linter.sh
  test/lib/validationTest.sh
Labels: enhancement, O: backlog 🤖

#5763 feat: add the kustomize binary for checkov
  .github/linters/.checkov-test-linters-success.yaml
  .github/linters/.checkov.yaml
  Dockerfile
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/checkov/bad/bad_kustomize/graph_check.yaml
  test/linters/checkov/bad/bad_kustomize/kustomization.yaml
  test/linters/checkov/good/good_kustomize/graph_check.yaml
  test/linters/checkov/good/good_kustomize/kustomization.yaml
Labels: enhancement, O: backlog 🤖
