Repository super-linter/super-linter, pull requests merged in 2024-05, with the labels that each got.

#5604 Ignore avif files when building file list
  lib/functions/buildFileList.sh
Labels: enhancement, O: backlog 🤖

#5628 Remove deployment configuration from ci
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: infrastructure, O: backlog 🤖

#5654 Fix a shadowing setting in .golangci.yml
  .github/linters/.golangci.yml
  TEMPLATES/.golangci.yml
  test/linters/go_modules/go_modules_bad/golang_bad_01.go
Labels: enhancement, O: backlog 🤖

#5629 Move local action test to a dedicated job
  .github/linters/.jscpd.json
  .github/workflows/ci.yml
Labels: infrastructure, automation, O: backlog 🤖

#5677 Update GitLab and Azure docs
  docs/run-linter-locally.md
Labels: documentation, O: backlog 🤖

#5674 feat: support for `POWERSHELL_CONFIG_FILE`
  README.md
  lib/linter.sh
Labels: enhancement, O: backlog 🤖

#5687 Run a job on test suite success
  .github/workflows/ci.yml
  test/linters/github_actions/actions_good_01.yml
Labels: bug, O: backlog 🤖

#5682 docs: update issue form to include version info
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request-template.md
Labels: documentation, O: backlog 🤖

#5689 deps(php): update php linters
  dependencies/phive.xml
  scripts/install-phive.sh
Labels: O: backlog 🤖, dependencies

#5655 Install lua from the os package repository
  scripts/install-lua.sh
Labels: infrastructure, O: backlog 🤖
