Repository super-linter/super-linter, pull requests merged in 2024-07, with the labels that each got.

#5839 docs: fix linting errors
  README.md
  docs/run-linter-locally.md
Labels: documentation, O: backlog 🤖

#5840 ci: check for skipped and cancelled matrix jobs
  .github/workflows/ci.yml
Labels: infrastructure, O: backlog 🤖

#5843 chore: fix linting errors
  test/linters/cloudformation/cloudformation_good_1.json
  test/linters/cloudformation/cloudformation_good_2.yaml
Labels: infrastructure

#5862 chore: fix docker build warnings
  Dockerfile
Labels: infrastructure, O: backlog 🤖

#5864 ci: run docker build checks
  Makefile
Labels: infrastructure, O: backlog 🤖

#5869 ci: print info about the environment, image size
  .github/workflows/ci.yml
  Makefile
Labels: infrastructure, O: backlog 🤖

#5868 feat: enable dotenv-linter for slim images
  .github/workflows/ci.yml
  Dockerfile
  README.md
  scripts/linterVersions.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: enhancement, O: backlog 🤖

#5870 fix: update the list of linters to remove
  lib/linter.sh
Labels: bug, O: backlog 🤖

#5871 ci: enable dev-dependencies docker build checks
  Makefile
  dev-dependencies/Dockerfile
Labels: infrastructure, O: backlog 🤖

#5867 feat: write github actions step summary
  .github/linters/.textlintrc
  .gitignore
  Makefile
  README.md
  lib/functions/validation.sh
  lib/linter.sh
  test/data/github-actions-step-summary/expected-step-summary-test-linters-expect-failure-slim.md
  test/data/github-actions-step-summary/expected-step-summary-test-linters-expect-failure-standard.md
  test/data/github-actions-step-summary/expected-step-summary-test-linters-expect-success-slim.md
  test/data/github-actions-step-summary/expected-step-summary-test-linters-expect-success-standard.md
  test/lib/validationTest.sh
  test/run-super-linter-tests.sh
Labels: enhancement, O: backlog 🤖

#5809 feat: remove no-eslintrc and simplify eslint conf
  TEMPLATES/.eslintrc.yml
  lib/functions/linterCommands.sh
Labels: enhancement, O: backlog 🤖

#5892 chore: split validation logic in smaller functions
  lib/functions/validation.sh
  lib/linter.sh
  test/lib/buildFileListTest.sh
  test/lib/detectFilesTest.sh
  test/lib/githubEventTest.sh
  test/lib/setupSSHTest.sh
  test/lib/validationTest.sh
Labels: infrastructure, O: backlog 🤖

#5894 ci: authenticate tflint init
  Dockerfile
Labels: infrastructure, O: backlog 🤖

#5901 ci: update release-please to the new workspace
  .github/workflows/cd.yml
Labels: automation, O: backlog 🤖, github_actions

#5679 feat: allow using both prettier and standardjs
  .github/linters/.jscpd.json
  .github/linters/commitlint.config.js
  README.md
  docs/upgrade-guide.md
  lib/functions/validation.sh
  lib/linter.sh
  test/data/github-actions-step-summary/expected-step-summary-test-linters-expect-failure-slim.md
  test/data/github-actions-step-summary/expected-step-summary-test-linters-expect-failure-standard.md
  test/data/github-actions-step-summary/expected-step-summary-test-linters-expect-success-slim.md
  test/data/github-actions-step-summary/expected-step-summary-test-linters-expect-success-standard.md
  test/linters/typescript_prettier/typescript_bad_1.ts
  test/linters/typescript_prettier/typescript_good_1.ts
Labels: enhancement, breaking, O: backlog 🤖

#5898 chore: update dependabot config for ci/dev updates
  .github/dependabot.yml
Labels: infrastructure, O: backlog 🤖

#5910 chore: add super-linter configuration in the bug template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: infrastructure, O: backlog 🤖

#5928 chore: remove duplicated configuration files
  .github/linters/.cfnlintrc.yml
  .github/linters/.chktexrc
  .github/linters/.ecrc
  .github/linters/.flake8
  .github/linters/.htmlhintrc
  .github/linters/.isort.cfg
  .github/linters/.lintr
  .github/linters/.luacheckrc
  .github/linters/.openapirc.yml
  .github/linters/.perlcriticrc
  .github/linters/.protolintrc.yml
  .github/linters/.python-black
  .github/linters/.python-lint
  .github/linters/.ruby-lint.yml
  .github/linters/.sql-config.json
  .github/linters/.sqlfluff
  .github/linters/.stylelintrc.json
  .github/linters/actionlint.yaml
  TEMPLATES/actionlint.yml
  test/linters/python_pylint/python_good_1.py
Labels: infrastructure, O: backlog 🤖

#5899 fix: store outputs in the main output directory
  Makefile
  README.md
  lib/functions/validation.sh
  lib/linter.sh
  test/lib/validationTest.sh
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#5939 fix: avoid duplicated content in summary
  Makefile
  README.md
  lib/functions/output.sh
  lib/linter.sh
  test/data/super-linter-summary/markdown/table/expected-summary-footer-failure.md
  test/data/super-linter-summary/markdown/table/expected-summary-footer-success.md
  test/data/super-linter-summary/markdown/table/expected-summary-heading.md
  test/data/super-linter-summary/markdown/table/expected-summary-line-failure.md
  test/data/super-linter-summary/markdown/table/expected-summary-line-success.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/outputTest.sh
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#5940 feat: customize phpstan config file name
  README.md
  lib/linter.sh
Labels: enhancement, O: backlog 🤖

#5927 fix: update pylint to ignore import-errors
  TEMPLATES/.python-lint
  test/linters/python_pylint/python_good_2.py
Labels: bug, O: backlog 🤖

#5944 docs: fix two default values in readme
  README.md
Labels: documentation, O: backlog 🤖

#5945 chore: extract language array definition
  Makefile
  docs/add-new-linter.md
  lib/globals/languages.sh
  lib/linter.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/buildFileListTest.sh
  test/lib/detectFilesTest.sh
  test/lib/githubEventTest.sh
  test/lib/globalsLanguagesTest.sh
  test/lib/outputTest.sh
  test/lib/setupSSHTest.sh
  test/lib/validationTest.sh
Labels: infrastructure, O: backlog 🤖
