Repository super-linter/super-linter, pull requests merged in 2024-04, with the labels that each got.

#5473 Do not print the whole environment
  lib/linter.sh
Labels: bug, O: backlog 🤖

#5481 Free more space on workers
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: automation, O: backlog 🤖

#5499 Export TEST_CASE_RUN
  lib/functions/buildFileList.sh
  lib/functions/linterVersions.sh
  lib/linter.sh
Labels: bug, O: backlog 🤖

#5456 Add support for astral-sh/ruff
  .github/linters/.jscpd.json
  Dockerfile
  README.md
  TEMPLATES/.ruff.toml
  dependencies/python/ruff.txt
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/linter.sh
  scripts/linterVersions.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/python_ruff/python_bad_1.py
  test/linters/python_ruff/python_good_1.py
Labels: enhancement, O: backlog 🤖

#5506 ci: do not run by pull request from fork
  .github/workflows/ci.yml
Labels: infrastructure, O: backlog 🤖

#5534 Handle initial commit
  Makefile
  lib/functions/buildFileList.sh
  lib/linter.sh
  test/lib/buildFileListTest.sh
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#5547 Wrap version info and logo with logs
  lib/linter.sh
Labels: bug, O: backlog 🤖

#5546 Respect log level and color support when writing to the log
  lib/functions/log.sh
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#5548 Configure ruff with a temp cache
  TEMPLATES/.ruff.toml
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#5571 Support arbitrary shellcheck config file paths
  README.md
  TEMPLATES/.shellcheckrc
  lib/functions/linterCommands.sh
  lib/linter.sh
  test/inspec/super-linter/controls/super_linter.rb
Labels: enhancement, O: backlog 🤖

#5345 Find go.mod based on Go files
  lib/functions/buildFileList.sh
Labels: enhancement, O: backlog 🤖

#5599 No full Git validation when ignoring files
  Makefile
  lib/linter.sh
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖
