Repository super-linter/super-linter, pull requests merged in 2024-01, with the labels that each got.

#5071 Install clang-format from OS package repo
  Dockerfile
  test/inspec/super-linter/controls/super_linter.rb
Labels: O: backlog 🤖, dependencies, docker

#5090 Add missing checkov configuration file
  Makefile
  TEMPLATES/.checkov.yaml
  test/inspec/super-linter/controls/super_linter.rb
Labels: bug, O: backlog 🤖

#5089 Use embedded checkstyle configuration files
  README.md
  TEMPLATES/sun_checks.xml
  lib/functions/linterRules.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/java/java_good_2.java
Labels: enhancement, O: backlog 🤖

#5091 Checkstyle upgrade notes
  docs/upgrade-guide.md
Labels: documentation

#5080 docs: fix README.md for slim action
  README.md
Labels: documentation, O: backlog 🤖

#5077 Uninstall eslint-config-airbnb-typescript
  dependencies/package-lock.json
  dependencies/package.json
  docs/upgrade-guide.md
  test/inspec/super-linter/controls/super_linter.rb
Labels: breaking, O: backlog 🤖, dependencies, javascript

#5093 Remove unneeded Node dependencies
  .github/workflows/trivy.yml
  dependencies/package-lock.json
  dependencies/package.json
  test/inspec/super-linter/controls/super_linter.rb
Labels: O: backlog 🤖, dependencies, javascript

#5096 Fix GITHUB_BEFORE_SHA initialization on push events
  .github/pull_request-template.md
  .github/workflows/ci.yml
  README.md
  lib/functions/buildFileList.sh
  lib/linter.sh
Labels: bug, O: backlog 🤖

#5098 Fix GITHUB_BEFORE_SHA initialization for push events
  .github/linters/.jscpd.json
  Makefile
  lib/functions/githubEvent.sh
  lib/functions/validation.sh
  lib/linter.sh
  test/data/github-event/github-event-push.json
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/githubEventTest.sh
  test/lib/validationTest.sh
Labels: bug, O: backlog 🤖

#5097 Add event name to concurrency group
  .github/workflows/ci.yml
Labels: automation, O: backlog 🤖

#5094 Don't inspect files if not needed
  Makefile
  lib/functions/detectFiles.sh
Labels: enhancement, O: backlog 🤖

#5100 Enable linting changed files with textlint
  docs/upgrade-guide.md
  lib/functions/buildFileList.sh
  test/linters/natural_language/natural_language_bad_01.md
  test/linters/natural_language/natural_language_good_01.md
Labels: bug, O: backlog 🤖

#5121 Fix concurrency group name
  .github/workflows/ci.yml
Labels: bug, O: backlog 🤖

#5078 Build and install dependencies in dedicated stages
  Dockerfile
  Makefile
  test/inspec/super-linter/controls/super_linter.rb
Labels: infrastructure, O: backlog 🤖

#5119 Simplify file status checks
  lib/functions/worker.sh
Labels: bug, O: backlog 🤖

#5117 Handle log messages in CheckFileType
  lib/functions/detectFiles.sh
Labels: bug, O: backlog 🤖

#5128 Validate variables and simplify lowercase
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/functions/validation.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: enhancement, O: backlog 🤖

#5127 Run versions command in the slim stage
  Dockerfile
Labels: automation, O: backlog 🤖

#5129 Standard image from base_image stage
  Dockerfile
Labels: automation, O: backlog 🤖

#5123 Simplify worker and linterVersions
  lib/functions/linterRules.sh
  lib/functions/linterVersions.sh
  lib/functions/worker.sh
  lib/linter.sh
Labels: bug, O: backlog 🤖

#5133 Cache more standard image layers
  Dockerfile
Labels: infrastructure, O: backlog 🤖

#4955 Implement two smoke tests for non-default settings
  Makefile
Labels: infrastructure, O: backlog 🤖

#5152 Update react native dependencies
  dependencies/package-lock.json
  dependencies/package.json
  test/inspec/super-linter/controls/super_linter.rb
Labels: O: backlog 🤖, dependencies, javascript

#5131 Simplify error code checks
  lib/functions/buildFileList.sh
  lib/functions/githubEvent.sh
  lib/functions/linterRules.sh
  lib/functions/linterVersions.sh
  lib/linter.sh
Labels: infrastructure, O: backlog 🤖

#5130 Simplify updateSSL
  Makefile
  lib/functions/setupSSH.sh
  lib/functions/updateSSL.sh
  test/data/ssl-certificate/rootCA-test.crt
Labels: infrastructure, O: backlog 🤖

#5132 Update devcontainer definition
  .devcontainer/README.md
  .devcontainer/devcontainer.env
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .vscode/launch.json
  .vscode/tasks.json
  .vscode/testlinter.sh
Labels: infrastructure, automation, O: backlog 🤖

#5177 Build the file list and run linters in parallel
  .github/linters/.checkov-test-linters-failure.yaml
  .github/linters/.checkov-test-linters-success.yaml
  .github/linters/.gitleaks-ignore-tests.toml
  .github/workflows/ci.yml
  .gitignore
  .gitleaksignore
  Dockerfile
  Makefile
  docs/add-new-linter.md
  docs/upgrade-guide.md
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/functions/linterCommands.sh
  lib/functions/log.sh
  lib/functions/validation.sh
  lib/functions/worker.sh
  lib/linter.sh
  test/inspec/super-linter/controls/super_linter.rb
  test/run-super-linter-tests.sh
Labels: enhancement, O: backlog 🤖

#5204 Ignore changelog when running textlint
  .textlintignore
Labels: infrastructure, O: backlog 🤖

#5205 Ignore changelog when linting codebase
  .github/release-please/release-please-config.json
  .textlintignore
  Makefile
Labels: infrastructure

#5206 Ignore changelog and tests when testing action
  .github/workflows/ci.yml
Labels: infrastructure

#5208 Clone the repository before tagging
  .github/workflows/cd.yml
Labels: automation
