Repository super-linter/super-linter, pull requests merged in 2025-09, with the labels that each got.

#7011 feat: add kubeconform
  .github/dependabot.yml
  .github/linters/.checkov.yaml
  .github/linters/trivy.yaml
  Dockerfile
  Makefile
  README.md
  docs/upgrade-guide.md
  lib/functions/buildFileList.sh
  lib/functions/detectFiles.sh
  lib/functions/linterCommands.sh
  lib/functions/validation.sh
  lib/globals/languages.sh
  scripts/linterVersions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/linterCommandsTest.sh
  test/linters/kubernetes_kubeconform/kubeconform_bad_1.yaml
  test/linters/kubernetes_kubeconform/kubeconform_good_1.yaml
Labels: enhancement, O: backlog 🤖

#7025 chore: simplify more tests
  .github/workflows/ci.yml
  Makefile
  README.md
  lib/functions/updateSSL.sh
  lib/linter.sh
  test/lib/updateSSLTest.sh
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: infrastructure, O: backlog 🤖

#7028 chore: simplify more tests
  Makefile
  test/lib/bashExecTest.sh
  test/lib/buildFileListTest.sh
  test/lib/linterCommandsTest.sh
  test/lib/osPackagesInstallationTest.sh
  test/run-super-linter-tests.sh
Labels: infrastructure, O: backlog 🤖

#7005 feat: support biome
  .github/dependabot.yml
  .gitignore
  Makefile
  README.md
  biome.json
  dependencies/package-lock.json
  dependencies/package.json
  docs/add-new-linter.md
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/functions/validation.sh
  lib/functions/worker.sh
  lib/globals/languages.sh
  lib/globals/linterCommandsOptions.sh
  scripts/linterVersions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-standard.md
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/biome_format/bad/bad.js
  test/linters/biome_format/good/good.js
  test/linters/biome_lint/bad/bad.js
  test/linters/biome_lint/biome.json
  test/linters/biome_lint/good/good.js
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: enhancement, O: backlog 🤖

#7039 docs: update .sqlfluff config link
  TEMPLATES/.sqlfluff
Labels: documentation, O: backlog 🤖

#7053 fix: initialize GITHUB_BEFORE_SHA on merge commits
  lib/functions/githubEvent.sh
  lib/functions/validation.sh
  lib/linter.sh
  test/lib/githubEventTest.sh
  test/lib/validationTest.sh
  test/testUtils.sh
Labels: bug, O: backlog 🤖

#7064 feat: add pre-commit
  .github/dependabot.yml
  .github/linters/.pre-commit-config-test-linters-failure.yaml
  .github/linters/.pre-commit-config-test-linters-success.yaml
  Dockerfile
  Makefile
  README.md
  TEMPLATES/.pre-commit-config.yaml
  dependencies/python/pre-commit.txt
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/globals/languages.sh
  lib/globals/linterCommandsOptions.sh
  lib/globals/linterRules.sh
  scripts/linterVersions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/linterCommandsTest.sh
  test/linters/pre_commit/bad/bad.json
  test/linters/pre_commit/good/good.txt
  test/run-super-linter-tests.sh
Labels: enhancement, O: backlog 🤖
