Repository super-linter/super-linter, pull requests merged in 2025-02, with the labels that each got.

#6557 chore: group commitlint updates
  .github/dependabot.yml
Labels: enhancement, O: backlog 🤖

#6563 chore: fix ansible dir ownership in tests
  test/run-super-linter-tests.sh
Labels: bug, O: backlog 🤖

#6573 chore: uninstall next-pwa and fix jest
  dependencies/package-lock.json
  dependencies/package.json
  test/inspec/super-linter/controls/super_linter.rb
Labels: O: backlog 🤖, dependencies, javascript

#6574 chore: fix checkov and sqlfluff tests
  test/linters/checkov/good/good_chart/templates/deployment.yaml
  test/linters/sqlfluff/sqlfluff_good_1.sql
Labels: infrastructure, O: backlog 🤖

#6408 feat: enable scss linting by default
  TEMPLATES/.stylelintrc.json
Labels: enhancement, O: backlog 🤖

#6580 chore: update go tests deps
  test/linters/go_modules/go_modules_bad/go.mod
  test/linters/go_modules/go_modules_bad/go.sum
  test/linters/go_modules/go_modules_good/go.mod
  test/linters/go_modules/go_modules_good/go.sum
Labels: bug, O: backlog 🤖

#6558 feat(golangci-lint): add possibility to specify custom config file
  README.md
  lib/globals/linterRules.sh
Labels: enhancement, O: backlog 🤖

#6594 chore: increase workflow timeouts to 120 mins
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/stale.yml
Labels: automation

#6204 fix: handle push tag events on merge commits
  Makefile
  lib/functions/githubEvent.sh
  lib/functions/worker.sh
  lib/linter.sh
  test/data/github-event/github-event-push-tag-merge-commit.json
  test/lib/validationTest.sh
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: bug, O: backlog 🤖

#6593 docs: update readme
  README.md
Labels: documentation, O: backlog 🤖

#6596 chore: remove deprecated golang-ci config value
  TEMPLATES/.golangci.yml
Labels: enhancement, O: backlog 🤖

#6326 Update run-linter-locally.md to include information about the default branch
  docs/run-linter-locally.md
Labels: documentation, O: backlog 🤖

#6599 feat: composer install with any php linters
  docs/run-linter-locally.md
  lib/functions/detectFiles.sh
Labels: enhancement, O: backlog 🤖

#6614 chore: fix ruby linting issues
  Makefile
  test/inspec/super-linter/controls/super_linter.rb
Labels: infrastructure, O: backlog 🤖
