Repository super-linter/super-linter, pull requests merged in 2025-01, with the labels that each got.

#6485 chore: update arm test api version
  test/linters/arm/arm_good_1.json
Labels: bug, O: backlog 🤖

#6475 Fix: Broken link on SQLFLUFF configuration
  README.md
Labels: documentation, O: backlog 🤖

#6514 chore: remove delete-branch option
  .github/workflows/dependabot-automation.yaml
Labels: automation, O: backlog 🤖, github_actions
