Repository super-linter/super-linter, pull requests merged in 2025-08, with the labels that each got.

#6923 chore: update python deps
  dependencies/python/ansible-lint.txt
  dependencies/python/snakefmt.txt
  dependencies/python/snakemake.txt
Labels: O: backlog 🤖, dependencies, python

#6908 chore: fix requirements word typo
  scripts/build-venvs.sh
Labels: infrastructure, O: backlog 🤖

#6925 feat: add trivy
  .github/linters/.checkov.yaml
  .github/linters/.trivyignore.yaml
  .github/linters/trivy-test-linters.yaml
  .github/linters/trivy.yaml
  Dockerfile
  README.md
  TEMPLATES/trivy.yaml
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/functions/worker.sh
  lib/globals/languages.sh
  lib/globals/linterRules.sh
  scripts/linterVersions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/inspec/super-linter/controls/super_linter.rb
  test/linters/trivy/bad/Dockerfile
  test/linters/trivy/good/Dockerfile
  test/run-super-linter-tests.sh
Labels: enhancement, O: backlog 🤖

#6943 feat: install os packages at run time
  .devcontainer/devcontainer.json
  Makefile
  README.md
  docs/install-additional-dependencies.md
  lib/functions/detectFiles.sh
  lib/functions/runtimeDependencies.sh
  lib/globals/runtimeDependencies.sh
  lib/linter.sh
  test/data/install-dependencies/os-packages/os-packages.json
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/osPackagesInstallationTest.sh
  test/testUtils.sh
Labels: enhancement, O: backlog 🤖

#6981 feat: run ruff as a formatter
  lib/functions/buildFileList.sh
  lib/functions/linterCommands.sh
  lib/functions/validation.sh
  lib/globals/languages.sh
  lib/globals/linterCommandsOptions.sh
  lib/globals/linterRules.sh
  scripts/linterVersions.sh
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-failure-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-expect-success-standard.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-slim.md
  test/data/super-linter-summary/markdown/table/expected-summary-test-linters-fix-mode-standard.md
  test/linters/python_ruff_format/ruff_format_bad_1.py
  test/linters/python_ruff_format/ruff_format_good_1.py
  test/testUtils.sh
Labels: enhancement, O: backlog 🤖

#6984 docs: add git worktrees section to local run documentation
  docs/run-linter-locally.md
Labels: documentation, O: backlog 🤖
