Repository super-linter/super-linter, pull requests merged in 2025-03, with the labels that each got.

#6619 JSON/JSONC: Support ESLint flat config files
  lib/functions/linterCommands.sh
Labels: enhancement, O: backlog 🤖

#6636 fix: emit prettier verbose output when debugging
  lib/functions/output.sh
Labels: bug, O: backlog 🤖

#6677 chore: update deps and fix devcontainer mounts
  Makefile
  dependencies/package-lock.json
Labels: infrastructure, O: backlog 🤖

#6669 chore: use python venv instead of virtualenv
  Dockerfile
  scripts/build-venvs.sh
Labels: infrastructure, O: backlog 🤖

#6675 fix: consider git dirs safe
  .github/linters/.golangci.yml
  Dockerfile
  lib/functions/buildFileList.sh
  lib/linter.sh
  test/linters/go_modules/go_modules_bad/go.mod
  test/linters/go_modules/go_modules_good/go.mod
Labels: bug, O: backlog 🤖

#6678 chore: cache multi-stage build
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: infrastructure, automation, O: backlog 🤖, github_actions

#6686 chore: login to container registry
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: bug, automation, O: backlog 🤖

#6689 chore: cache the base image stage
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Makefile
Labels: automation, O: backlog 🤖

#6693 fix: more robust error checking and test fixes
  Makefile
  lib/functions/githubEvent.sh
  lib/functions/validation.sh
  lib/linter.sh
  test/data/github-event/github-event-pull-request-multiple-commits.json
  test/lib/buildFileListTest.sh
  test/lib/githubEventTest.sh
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: bug, O: backlog 🤖

#6637 feat: do not hide php composer output
  lib/functions/detectFiles.sh
Labels: enhancement, O: backlog 🤖

#6697 fix: check return code and misc test improvements
  README.md
  lib/linter.sh
  test/data/test-repository-contents/json_good_1.json
  test/lib/buildFileListTest.sh
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: bug, O: backlog 🤖
