Repository super-linter/super-linter, pull requests merged in 2025-04, with the labels that each got.

#6714 fix: export github_before_sha
  Makefile
  lib/functions/validation.sh
  lib/linter.sh
  test/data/github-event/github-event-push-multiple-commits.json
  test/lib/buildFileListTest.sh
  test/lib/validationTest.sh
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: bug, O: backlog 🤖

#6687 feat: set github_before_sha on pull requests
  lib/functions/buildFileList.sh
  lib/functions/validation.sh
  lib/linter.sh
  test/lib/buildFileListTest.sh
  test/lib/validationTest.sh
Labels: enhancement, O: backlog 🤖

#6732 chore: free disk space
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: infrastructure, O: backlog 🤖, github_actions

#6733 fix: check if commit count is defined before using
  Makefile
  lib/functions/validation.sh
  lib/linter.sh
  test/data/github-event/github-event-merge-group.json
  test/run-super-linter-tests.sh
  test/testUtils.sh
Labels: bug, O: backlog 🤖

#6746 chore: update readme
  README.md
Labels: documentation, O: backlog 🤖

#6730 fix: update deprecated default file name for editorconfig
  README.md
  TEMPLATES/.editorconfig-checker.json
  docs/upgrade-guide.md
  lib/functions/validation.sh
  lib/globals/linterRules.sh
  lib/linter.sh
  test/data/deprecated-linter-rules-test/.ecrc
  test/inspec/super-linter/controls/super_linter.rb
  test/lib/validationTest.sh
Labels: bug, O: backlog 🤖
